CONTRIBUTING.md
requirements-dev.txt
tox.ini

I add three files in this PR: CONTRIBUTING.md, requirements-dev.txt, and tox.ini.

Adding contribution guide

---

setup.py
verticapy/connections/connect.py
verticapy/errors.py
verticapy/learn/cluster.py
verticapy/learn/ensemble.py
verticapy/learn/linear_model.py
verticapy/learn/metrics.py
verticapy/learn/model_selection.py
verticapy/learn/naive_bayes.py
verticapy/learn/neighbors.py
verticapy/learn/plot.py
verticapy/learn/svm.py
verticapy/plot.py
verticapy/sql.py
verticapy/toolbox.py
verticapy/utilities.py
verticapy/vCharts.py
verticapy/vcolumn.py
verticapy/vdataframe.py

Many Modifications:
- More precise Errors
- Matplotlib Graphics are now returned
- Limit number of elements to display
- ...

Preparing Version 0.1

---

verticapy/tests/vDataFrame/test_vDF_feature_engineering.py
verticapy/tests/vModel/test_vM_tsa_tools.py
verticapy/toolbox.py
verticapy/vdataframe.py

- Correcting bugs of analytics and rolling
- Correcting the tests to fix the order (in order to have one unique result, the columns used to order must represent a unique value)

Correcting tests and bugs

---

verticapy/tests/vDataFrame/test_vDF_feature_engineering.py
verticapy/tests/vDataFrame/test_vDF_utilities.py
verticapy/vdataframe.py

- Adding test to_db
- correcting method corr, beta, ... for rolling and analytics (no useless columns created and corrected a parenthesis mistake which leaded to wrong results)
- Correcting test features_engineering

Test Units 5

---

setup.py
verticapy/__init__.py
verticapy/connections/connect.py
verticapy/learn/cluster.py
verticapy/learn/neighbors.py
verticapy/learn/tsa/models.py
verticapy/learn/vmodel.py
verticapy/plot.py
verticapy/tests/vDataFrame/test_vDF_plot.py
verticapy/tests/vDataFrame/test_vDF_preprocessing.py
verticapy/toolbox.py
verticapy/utilities.py
verticapy/vcolumn.py
verticapy/vdataframe.py

- ADD HEATMAP
- ADD KernelDensity
- Correction orientation pivot_table
- get_tree BKTree
- Adding warnings
- vcolumn density parameters
- discretize - Tree
- density for vDataFrame

pushing for v0.3

---

setup.py
verticapy/__init__.py
verticapy/learn/cluster.py
verticapy/learn/model_selection.py
verticapy/learn/neighbors.py
verticapy/learn/preprocessing.py
verticapy/learn/tsa/models.py
verticapy/learn/vmodel.py
verticapy/plot.py
verticapy/sql.py
verticapy/stats.py
verticapy/tests/stats/__init__.py
verticapy/tests/stats/test_stats.py
verticapy/tests/vDataFrame/test_vDF_combine_join_sort.py
verticapy/tests/vDataFrame/test_vDF_feature_engineering.py
verticapy/tests/vDataFrame/test_vDF_filter_sample.py
verticapy/tests/vDataFrame/test_vDF_preprocessing.py
verticapy/tests/vDataFrame/test_vDF_utilities.py
verticapy/toolbox.py
verticapy/utilities.py
verticapy/vcolumn.py
verticapy/vdataframe.py

- Adding random state
- Adding stats package
- simplifying the code

Preparing 0.3.2

---

verticapy/__init__.py
verticapy/learn/metrics.py
verticapy/learn/model_selection.py
verticapy/learn/vmodel.py
verticapy/stats.py
verticapy/tests/stats/test_stats.py
verticapy/tests/vDataFrame/test_vDF_feature_engineering.py
verticapy/tests/vDataFrame/test_vDF_filter_sample.py
verticapy/tests/vDataFrame/test_vDF_utilities.py
verticapy/toolbox.py
verticapy/utilities.py
verticapy/vcolumn.py
verticapy/vdataframe.py

- Adding some math functions
- Correcting some bugs
- Adding UT

Finalizing v0.3.2

---

verticapy/learn/pipeline.py
verticapy/learn/preprocessing.py
verticapy/learn/vmodel.py
verticapy/tests/udf/__init__.py
verticapy/tests/udf/pmath.py
verticapy/tests/udf/test_udf.py
verticapy/tests/vDataFrame/test_vDF_utilities.py
verticapy/tests/vModel/test_logistic_regression.py
verticapy/tests/vModel/test_pipeline.py
verticapy/toolbox.py
verticapy/udf.py
verticapy/vdataframe.py

- Correcting Pipelines
- Correcting One Hot Encoder
- Correcting Preprocessing techniques
- Adding the UT for udf

Pipeline + Preprocessing + UDF UT

---

verticapy/geo.py
verticapy/learn/linear_model.py
verticapy/learn/metrics.py
verticapy/learn/model_selection.py
verticapy/learn/pipeline.py
verticapy/learn/tsa/tools.py
verticapy/learn/vmodel.py
verticapy/tests/vModel/test_decision_tree_regressor.py
verticapy/tests/vModel/test_dummy_tree_classifier.py
verticapy/tests/vModel/test_dummy_tree_regressor.py
verticapy/tests/vModel/test_elastic_net.py
verticapy/tests/vModel/test_lasso.py
verticapy/tests/vModel/test_linear_regression.py
verticapy/tests/vModel/test_linear_svc.py
verticapy/tests/vModel/test_linear_svr.py
verticapy/tests/vModel/test_logistic_regression.py
verticapy/tests/vModel/test_normalizer.py
verticapy/tests/vModel/test_onehotencoder.py
verticapy/tests/vModel/test_pca.py
verticapy/tests/vModel/test_ridge.py
verticapy/tests/vModel/test_svd.py
verticapy/udf.py

Small Correction
- set_parameters
- some tests
- udf

Small corrections

---

verticapy/connections/connect.py
verticapy/learn/metrics.py
verticapy/learn/model_selection.py
verticapy/learn/plot.py
verticapy/learn/vmodel.py
verticapy/plot.py
verticapy/tests/vDataFrame/test_vDF_combine_join_sort.py
verticapy/tests/vDataFrame/test_vDF_descriptive_statistics.py
verticapy/tests/vDataFrame/test_vDF_plot.py
verticapy/tests/vModel/test_bisecting_kmeans.py
verticapy/tests/vModel/test_decision_tree_classifier.py
verticapy/tests/vModel/test_dummy_tree_classifier.py
verticapy/tests/vModel/test_elastic_net.py
verticapy/tests/vModel/test_lasso.py
verticapy/tests/vModel/test_linear_regression.py
verticapy/tests/vModel/test_linear_svc.py
verticapy/tests/vModel/test_linear_svr.py
verticapy/tests/vModel/test_logistic_regression.py
verticapy/tests/vModel/test_model_selection.py
verticapy/tests/vModel/test_randomforest_classifier.py
verticapy/tests/vModel/test_ridge.py
verticapy/vcolumn.py
verticapy/vdataframe.py

- New UT: Model Selections + New plots
New functions:
- model_selection: cross_validate / grid_search / validation_curve
- vModel: cutoff_curve
- vcolumn: range_plot
- vdf: outliers_plot / pie / polynomial_comb / recommend / stacked_area
Correction Bugs:
- BisectingKMeans
New design for general plots

Preparing v0.4.2 -New Functions + UT

---

.github/workflows/ci.yaml
.github/workflows/master-codecov.yml

Upgrade the server version of CI from `10.0.1` to `10.1`.

Upgrade test framework

---

setup.py
verticapy/__init__.py
verticapy/learn/metrics.py
verticapy/learn/mlplot.py
verticapy/learn/model_selection.py
verticapy/learn/neighbors.py
verticapy/learn/pipeline.py
verticapy/learn/vmodel.py
verticapy/tests/vModel/test_decision_tree_classifier.py
verticapy/tests/vModel/test_decision_tree_regressor.py
verticapy/tests/vModel/test_dummy_tree_classifier.py
verticapy/tests/vModel/test_dummy_tree_regressor.py
verticapy/tests/vModel/test_linear_svc.py
verticapy/tests/vModel/test_logistic_regression.py
verticapy/tests/vModel/test_naive_bayes.py
verticapy/tests/vModel/test_onehotencoder.py
verticapy/tests/vModel/test_pipeline.py
verticapy/tests/vModel/test_randomforest_classifier.py
verticapy/tests/vModel/test_randomforest_regressor.py
verticapy/tests/vModel/test_xgb_classifier.py
verticapy/tests/vModel/test_xgb_regressor.py
verticapy/utilities.py
verticapy/vdataframe.py

- Display Bug for autoML - corrected
- Adding to_python for Pipelines
- to_python is now available for NaiveBayes and OneHotEncoder
- correction to_sql for OneHotEncoder
- correction of read_csv for headers with space
- correction of outlier_plot

Multiple corrections and code completion

---

setup.py
verticapy/__init__.py
verticapy/hchart.py
verticapy/learn/delphi.py
verticapy/learn/ensemble.py
verticapy/learn/metrics.py
verticapy/learn/mlplot.py
verticapy/learn/model_selection.py
verticapy/learn/neighbors.py
verticapy/learn/pipeline.py
verticapy/learn/preprocessing.py
verticapy/learn/tree.py
verticapy/learn/tsa.py
verticapy/learn/vmodel.py
verticapy/plot.py
verticapy/sql.py
verticapy/stats/tools.py
verticapy/tests/vDataFrame/test_vDF_descriptive_statistics.py
verticapy/udf.py
verticapy/utilities.py
verticapy/vcolumn.py
verticapy/vdataframe.py

- correction %sql
- correction AutoML
- correction cvar
- correction types hint
- correction read_csv
- insert available in to_db

Multiple corrections

---

CONTRIBUTING.md
verticapy/connect.py
verticapy/learn/cluster.py
verticapy/learn/decomposition.py
verticapy/learn/mlplot.py
verticapy/learn/neighbors.py
verticapy/learn/vmodel.py
verticapy/plot.py
verticapy/tests/vModel/test_knn_classifier.py
verticapy/tests/vModel/test_knn_regressor.py
verticapy/tests/vModel/test_mca.py
verticapy/tests/vModel/test_nearestcentroid.py
verticapy/tests/vModel/test_pca.py
verticapy/tests/vModel/test_svd.py
verticapy/toolbox.py
verticapy/utilities.py
verticapy/vcolumn.py
verticapy/vdataframe.py

- Changing directory for storing the credentials, it is now stored in user-side
- adding MCA with many new plotting methods (plot_cos2, plot_contrib, plot_var)
- inplace parameters for KNN
- method plot_scree for Decomposition models
- _not_in for vdf
- correction bug SQL magic
- scatter possibles with PCA (new parameter for scatter plot)

Changes for version 063

---

examples/use-cases/Credit_card_fraud.ipynb
setup.py
verticapy/__init__.py
verticapy/learn/memmodel.py
verticapy/learn/metrics.py
verticapy/learn/model_selection.py
verticapy/learn/tools.py
verticapy/learn/vmodel.py
verticapy/sql.py
verticapy/tests/utilities/test_utilities.py
verticapy/tests/vDataFrame/test_vDF_correlation.py
verticapy/tests/vDataFrame/test_vDF_preprocessing.py
verticapy/tests/vModel/test_balance.py
verticapy/tests/vModel/test_memmodel.py
verticapy/tests/vModel/test_naive_bayes.py
verticapy/tests/vModel/test_tools.py
verticapy/tests/vModel/test_xgb_classifier.py
verticapy/toolbox.py
verticapy/utilities.py
verticapy/vcolumn.py
verticapy/vdataframe.py

New method: vdf.pivot_table_chi2
New params:
pandas_to_vertica: name, schema
read_csv, read_json, pcsv, pjson: ingest_local
score, roc_curve, auc: nbins
Main Feature:
MemModel
Issues closed: 140, 138, 143, 151, 139, 153, 152, 150, 154, 145, 156, 157

Version v0.7.0

---

verticapy/learn/ensemble.py

UT will be done in the next days.

Adding the to_JSON function

---

verticapy/geo.py
verticapy/learn/delphi.py
verticapy/learn/metrics.py
verticapy/learn/model_selection.py
verticapy/learn/neighbors.py
verticapy/learn/vmodel.py
verticapy/tests/utilities/test_utilities.py
verticapy/tests/vDataFrame/test_vDF_preprocessing.py
verticapy/tests/vDataFrame/test_vDF_utilities.py
verticapy/tests/vModel/test_countvectorizer.py
verticapy/tests/vModel/test_knn_classifier.py
verticapy/tests/vModel/test_knn_regressor.py
verticapy/tests/vModel/test_linear_svc.py
verticapy/tests/vModel/test_logistic_regression.py
verticapy/tests/vModel/test_nearestcentroid.py
verticapy/tests/vModel/test_pipeline.py
verticapy/tests/vModel/test_sarimax.py
verticapy/tests/vModel/test_var.py
verticapy/toolbox.py
verticapy/utilities.py
verticapy/vdataframe.py

- pandas_to_vertica
Solves #265 #260 #253 #197
- Flex Tables name
Solves #186
- public schema issues
Solves #209
- precision error
Solves #216
- predict & get_attr method of KNN
Solves #223 #262
- sampling
Solves #254 #255

Correcting multiple issues (bug + improvements)

---

verticapy/datasets.py
verticapy/learn/delphi.py
verticapy/plot.py
verticapy/tests/vDataFrame/test_vDF_plot.py
verticapy/tests/vDataFrame/test_vDF_preprocessing.py
verticapy/utilities.py
verticapy/vcolumn.py
verticapy/vdataframe.py

- nbins instead of bins (some functions were using one some other the other)
- adding relation_type in function drop (same here)
Can you please release the new version when you approve the PR?

Unifying the API Parameters name

---

setup.py
verticapy/__init__.py
verticapy/highchart.py
verticapy/learn/model_selection.py
verticapy/sql.py
verticapy/utilities.py

Solves #327, #328, #326, #325
- I named the version 0.9.0-0 to avoid collisions when pulling it. The final one will be 0.9.1
- Correcting the different bugs listed above.

Correcting many bugs

---

setup.py
verticapy/__init__.py
verticapy/connect.py
verticapy/hchart.py
verticapy/highchart.py
verticapy/learn/ensemble.py
verticapy/learn/memmodel.py
verticapy/learn/model_selection.py
verticapy/learn/pipeline.py
verticapy/learn/tools.py
verticapy/learn/tree.py
verticapy/learn/vmodel.py
verticapy/sql.py
verticapy/tests/hchart/test_hchart.py
verticapy/tests/sql/test_sql.py
verticapy/tests/vDataFrame/test_vDF_create.py
verticapy/tests/vDataFrame/test_vDF_plot.py
verticapy/tests/vModel/test_iforest.py
verticapy/toolbox.py
verticapy/utilities.py
verticapy/vdataframe.py

- Adding all the methods for Isolation Forest
- Indenting the code
@afard can you please review the code? I am not sure for the scoring method.
@ansleis can you please review the new descriptions in the files: ensemble.py, memmodel.py
TODO:
Adding the tests when the 12.x RPM is available

Isolation Forest

---

setup.py
verticapy/__init__.py
verticapy/learn/ensemble.py
verticapy/learn/vmodel.py
verticapy/tests/sql/test_sql.py
verticapy/tests/vModel/test_iforest.py
verticapy/utilities.py
verticapy/vdataframe.py

- Alias for narrow = melt
- Correction of multiple bugs: pandas_to_vertica, graphics colors, ...
- new methods deploySQL , predict and decision_function for iForest (support of threshold and contamination parameters).
TODO: SQL Magic bug
@ansleis can you please review the doc of the different functions?

Bug Corrections + New Methods for iForest

---

verticapy/tests/vDataFrame/test_vDF_combine_join_sort.py
verticapy/utilities.py
verticapy/vdataframe.py

Last PR before v0.10.2

---

verticapy/learn/tools.py
verticapy/tests/sql/test_sql.py
verticapy/tests/utilities/test_utilities.py
verticapy/tests/vDataFrame/test_vDF_utilities.py
verticapy/utilities.py
verticapy/vcolumn.py
verticapy/vdataframe.py

- New parameters: flex_name and genSQL for pcsv
- New parameters genSQL and materialize for read_csv and read_json
- New parameters insert, ingest_local for read_file
- Correction of some bugs
TODO:
unitests for read_csv, read_json, read_file, to_csv, to_json

Improving read_csv, read_json and read_file

---

verticapy/tests/utilities/test_utilities.py
verticapy/vdataframe.py

Support of to_db for flex

---

verticapy/stats/math.py
verticapy/tests/sql/test_sql.py
verticapy/tests/stats/test_stats.py
verticapy/tests/vDataFrame/test_vDF_combine_join_sort.py
verticapy/tests/vDataFrame/test_vDF_utilities.py
verticapy/utilities.py
verticapy/vdataframe.py

- Formatting the code
- Jaro + Jaro Winkler distances
- vdf.join: improvement new operators

Jaro Winkler + vdf.join

---

verticapy/tests/vDataFrame/test_vDF_combine_join_sort.py
verticapy/utilities.py

read_csv new parameters

---

verticapy/datasets.py
verticapy/utilities.py
verticapy/vcolumn.py
verticapy/vdataframe.py

- Bug on flat_vmap => isvmap
- typo corrections of some functions

Bug + Doc Correction

---

setup.py
verticapy/__init__.py
verticapy/toolbox.py
verticapy/utilities.py
verticapy/vcolumn.py
verticapy/vdataframe.py

- Save to Query Profile: new parameter in set_option to choose either to save all the logs or partially some of them. Also, It does not affect the "print_sql" option anymore.
- Flex Table: better vmap guessing, flat vmap can now exclude some columns.
- read_csv: guess automatically the delimiter whenever it is possible.
For the doc:
- New param exclude_columns for vDataFrame.flat_vmap
- Parameter sep changed for read_csv function.
- New option for the set_option function.
TODO:
- Unit test for read_csv
- Unit test on the exclude of flat_vmap

Correction of multiple small issues

---

README.md
verticapy/toolbox.py
verticapy/utilities.py

- Small typo corrections
- New tool box function to help on the issue #418

Small corrections + new toolbox functions.

---

setup.py
verticapy/__init__.py
verticapy/tests/vDataFrame/test_vDF_preprocessing.py
verticapy/toolbox.py
verticapy/vdataframe.py

- changing version => 0.12.0 as too many features are released
- adding new function merge_similar_names

merge_similar_names

---

.github/workflows/ci.yaml
setup.py
tox.ini
verticapy/connect.py
verticapy/learn/tools.py
verticapy/utilities.py
verticapy/vcolumn.py
verticapy/vdataframe.py

- Reducing the number of save_to_query_profile calls. Specifically for the basic functions
- adding more doc info / correcting some doc error

Solving SAVE TO QUERY PROFILE problem

---

verticapy/learn/memmodel.py
verticapy/learn/model_selection.py
verticapy/learn/tools.py
verticapy/learn/vmodel.py
verticapy/tests/vModel/test_kprototypes.py

- Unit Tests still missing
- code formatting using BLACK

KPrototypes PART 2

---

verticapy/learn/vmodel.py
verticapy/tests/vModel/test_randomforest_classifier.py
verticapy/tests/vModel/test_randomforest_regressor.py
verticapy/tests/vModel/test_xgb_classifier.py
verticapy/tests/vModel/test_xgb_regressor.py

- XGB Features Importance for XGBoost
- New method for trees get_score to get the predictors different metrics

Features Importance Update

---

verticapy/datasets.py
verticapy/decorators.py
verticapy/geo.py
verticapy/hchart.py
verticapy/highchart.py
verticapy/learn/cluster.py
verticapy/learn/decomposition.py
verticapy/learn/delphi.py
verticapy/learn/ensemble.py
verticapy/learn/linear_model.py
verticapy/learn/memmodel.py
verticapy/learn/metrics.py
verticapy/learn/naive_bayes.py
verticapy/learn/pipeline.py
verticapy/learn/preprocessing.py
verticapy/learn/tools.py
verticapy/sql.py
verticapy/tests/vModel/test_countvectorizer.py
verticapy/toolbox.py
verticapy/utilities.py
verticapy/vcolumn.py
verticapy/vdataframe.py

- Still improving queries
- formatting correctly the code
- improving imports

optimization - Part 5

---

verticapy/highchart.py
verticapy/javascript.py
verticapy/learn/memmodel.py
verticapy/learn/mlplot.py
verticapy/learn/model_selection.py
verticapy/learn/neighbors.py
verticapy/learn/pipeline.py
verticapy/learn/tsa.py
verticapy/learn/vmodel.py
verticapy/stats/math.py
verticapy/tests/vModel/test_knn_classifier.py
verticapy/tests/vModel/test_knn_regressor.py
verticapy/vcolumn.py

- same as previous
- trying to format correctly the code and erase redundancy.

Optimisation - PART 5

---

verticapy/core/vdataframe/_corr.py
verticapy/core/vdataframe/_plotting.py
verticapy/machine_learning/metrics/plotting.py
verticapy/machine_learning/model_selection/hp_tuning/plotting.py
verticapy/machine_learning/model_selection/kmeans.py
verticapy/machine_learning/model_selection/model_validation.py
verticapy/machine_learning/model_selection/variables_selection.py
verticapy/machine_learning/vertica/decomposition.py
verticapy/plotting/_matplotlib/scatter.py
verticapy/tests/vDataFrame/test_vDF_plot.py

- histogram draws now only histogram.
- bar chart and horizontal bar charts have their own functions
- starting to support Plotly.

PLOTTING: Cleaning the different functions.

---

setup.py
tox.ini
verticapy/plotting/_plotly/bar.py
verticapy/tests/vDataFrame/test_vDF_plot_plotly.py

- Added code for plotly integration of bar chart
- Added unit tests

Plotly Integration for Bar plot

---

verticapy/core/vdataframe/_plotting.py
verticapy/plotting/_plotly/__init__.py
verticapy/plotting/_plotly/pie.py
verticapy/tests/vDataFrame/test_vDF_plot_plotly.py

Continuing plotly integration in Verticapy
Added code for 1D pie chart
Unit tests for 1D pie chart

plotly integration continues - pie chart

---

verticapy/core/vdataframe/_plotting.py
verticapy/machine_learning/model_selection/variables_selection.py
verticapy/machine_learning/vertica/automl/supervised.py
verticapy/machine_learning/vertica/base.py
verticapy/machine_learning/vertica/cluster.py
verticapy/machine_learning/vertica/decomposition.py
verticapy/machine_learning/vertica/ensemble.py
verticapy/machine_learning/vertica/linear_model.py
verticapy/machine_learning/vertica/neighbors.py
verticapy/plotting/_matplotlib/__init__.py
verticapy/plotting/_matplotlib/boxplot.py
verticapy/plotting/_matplotlib/contour_plot.py
verticapy/plotting/_matplotlib/machine_learning/champion_challenger.py
verticapy/plotting/_matplotlib/machine_learning/kmeans.py
verticapy/plotting/_matplotlib/machine_learning/lof.py
verticapy/plotting/_matplotlib/machine_learning/pca.py
verticapy/plotting/_matplotlib/machine_learning/regression.py
verticapy/plotting/_matplotlib/machine_learning/regression_tree.py
verticapy/plotting/_matplotlib/machine_learning/stepwise.py
verticapy/plotting/_matplotlib/outliers.py
verticapy/plotting/_matplotlib/pie.py
verticapy/plotting/_matplotlib/scatter.py
verticapy/plotting/_plotly/bar.py
verticapy/plotting/_utils.py
verticapy/plotting/base.py
verticapy/tests/vDataFrame/test_vDF_plot_plotly.py
verticapy/tests/vModel/test_iforest.py

- Supporting contour plot / nested pie.
- Improving BoxPlots.
- Supporting stepwise, Champion Challenger, regression, regression tree plot, pca plots.
TODO:
- improve nested pie aggregate computations.
- animated plots
- logit plot
- importance plot
- Svm plot

PLOTTING: Code Cleaning & Improvement

---

verticapy/plotting/_plotly/__init__.py
verticapy/plotting/_plotly/barh.py
verticapy/tests/vDataFrame/test_vDF_plot_plotly.py

- added code for 1d horizontal bar chart
- added unit test

plotly integration - horizontal bar chart

---

verticapy/plotting/_plotly/__init__.py
verticapy/plotting/_plotly/base.py
verticapy/plotting/_plotly/scatter.py
verticapy/tests/vDataFrame/test_vDF_plot_plotly.py

Plotly integration for scatter plots
- added 2d scatter plot
- added 3d scatter plot
- unit tests for scatter plots
- added format_class function to base class format column names

Plotly scatter

---

verticapy/core/vdataframe/_plotting.py
verticapy/machine_learning/vertica/decomposition.py
verticapy/plotting/_matplotlib/bar.py
verticapy/plotting/_plotly/bar.py
verticapy/plotting/_plotly/barh.py
verticapy/plotting/_plotly/base.py
verticapy/plotting/_plotly/pie.py
verticapy/plotting/_plotly/scatter.py
verticapy/plotting/base.py
verticapy/tests/vDataFrame/test_vDF_plot.py
verticapy/tests/vDataFrame/test_vDF_plot_plotly.py

- adding new params categorical and bargap for bar and barh
- erasing quotes from the columns name (better rendering)
- correcting compute_plot_params: NULL are now correctly represented.
- code formatting using black

PLOTTING: Code Cleaning + New Parameters.

---

setup.py
verticapy/__init__.py
verticapy/core/vdataframe/_corr.py
verticapy/core/vdataframe/_plotting.py
verticapy/machine_learning/model_selection/statistical_tests/tsa.py
verticapy/plotting/_highcharts/__init__.py
verticapy/plotting/_highcharts/bar.py
verticapy/plotting/_highcharts/barh.py
verticapy/plotting/_highcharts/boxplot.py
verticapy/plotting/_highcharts/heatmap.py
verticapy/plotting/_highcharts/line.py
verticapy/plotting/_highcharts/pie.py
verticapy/plotting/_highcharts/spider.py
verticapy/plotting/_matplotlib/acf.py
verticapy/plotting/_matplotlib/barh.py
verticapy/plotting/_matplotlib/heatmap.py
verticapy/plotting/_matplotlib/line.py
verticapy/plotting/_plotly/pie.py
verticapy/plotting/_utils.py
verticapy/plotting/base.py
verticapy/tests/connect/test_connect.py
verticapy/tests/vDataFrame/test_vDF_correlation.py
verticapy/tests/vDataFrame/test_vDF_plot.py

- Supporting HC HeatMap, 1D Pie, Negative Bar, BoxPlot, Line & Spider.
- Correcting Matplotlib HeatMap.
- making the API consistent with the same parameters names.
TODO:
- graphical function should use a general object plot_obj rather than 'ax' which is only for Matplotlib.
- range plot and stacked range.
- scatter.

HIGHCHARTS: Supporting HeatMap | 1D Pie | Negative Bar | Spider | BoxPlot | Line

---

verticapy/core/vdataframe/_plotting.py
verticapy/machine_learning/vertica/cluster.py
verticapy/plotting/_highcharts/__init__.py
verticapy/plotting/_highcharts/line.py
verticapy/plotting/_highcharts/range.py
verticapy/plotting/_highcharts/scatter.py
verticapy/plotting/_matplotlib/scatter.py
verticapy/plotting/_plotly/scatter.py
verticapy/plotting/base.py
verticapy/tests/vDataFrame/test_vDF_plot.py
verticapy/tests/vDataFrame/test_vDF_plot_plotly.py

- New HC plots: RANGE | AREA | SCATTER
- Improving Boxplots
- deleting the 'stacked_area' function to add options to the 'plot' one.
- add step plot for highchart.
- normalising parameters names.
TODO:
- add candlestick
- drilldown charts

PLOTTING: Highcharts new plots RANGE | AREA | SCATTER

---

verticapy/machine_learning/model_selection/variables_selection.py
verticapy/machine_learning/vertica/automl/supervised.py
verticapy/plotting/_highcharts/__init__.py
verticapy/plotting/_highcharts/machine_learning/champion_challenger.py
verticapy/plotting/_highcharts/machine_learning/stepwise.py
verticapy/plotting/base.py

- Support of Champion Challenger | Stepwise PLOTs.
- Correction of plot importance.
TODO:
- Simplify HC Styling.
-> END OF HC Integration.

PLOTTING: Highcharts - New Graphics

---

verticapy/plotting/_plotly/bar.py
verticapy/plotting/_plotly/barh.py
verticapy/plotting/_plotly/base.py
verticapy/plotting/_plotly/boxplot.py
verticapy/plotting/_plotly/pie.py
verticapy/plotting/_plotly/scatter.py

- create a plotly.graph_object for all plots
- this enables working on a user provided figure object

created consistent figure object

---

verticapy/plotting/_plotly/__init__.py
verticapy/plotting/_plotly/base.py
verticapy/plotting/_plotly/heatmap.py
verticapy/tests/vDataFrame/test_vDF_plot_plotly.py

PLOTTING: Plotly Integration - Heatmap

---

verticapy/plotting/_plotly/bar.py
verticapy/plotting/_plotly/boxplot.py
verticapy/plotting/_plotly/line.py
verticapy/plotting/_plotly/pie.py
verticapy/plotting/_plotly/scatter.py

- made bar plot width more intuitive
- added custom width option for boxplot and scatter
- added unit test for custom width and height

custom width and height

---

verticapy/plotting/_plotly/__init__.py
verticapy/plotting/_plotly/contour_plot.py
verticapy/tests/vDataFrame/test_vDF_plot_plotly.py

plotly integration - contour plot

---

verticapy/plotting/_plotly/__init__.py
verticapy/plotting/_plotly/density.py
verticapy/tests/vDataFrame/test_vDF_plot_plotly.py

- added 1d density plot, multi plot

plotly integration - 1d density plot

---

verticapy/plotting/_plotly/__init__.py
verticapy/plotting/_plotly/spider.py
verticapy/tests/vDataFrame/test_vDF_plot_plotly.py

plotly integration - spider

---

verticapy/core/vdataframe/_plotting.py
verticapy/plotting/_plotly/__init__.py
verticapy/plotting/_plotly/range.py
verticapy/tests/vDataFrame/test_vDF_plot_plotly.py

- added range plot 
- added unit test
- fixed bugs from previously undetected unit tests
TODO:
- fix bugs in line plots

Plotly Integration - range plot

---

verticapy/core/vdataframe/_aggregate.py
verticapy/core/vdataframe/_encoding.py
verticapy/core/vdataframe/_eval.py
verticapy/core/vdataframe/_fill.py
verticapy/core/vdataframe/_filter.py
verticapy/core/vdataframe/_io.py
verticapy/core/vdataframe/_math.py
verticapy/core/vdataframe/_multiprocessing.py
verticapy/core/vdataframe/_normalize.py
verticapy/core/vdataframe/_pivot.py
verticapy/core/vdataframe/_plotting.py
verticapy/core/vdataframe/_read.py
verticapy/core/vdataframe/_rolling.py
verticapy/core/vdataframe/_sys.py
verticapy/core/vdataframe/_text.py
verticapy/core/vdataframe/_typing.py
verticapy/core/vdataframe/_utils.py
verticapy/core/vdataframe/base.py
verticapy/machine_learning/metrics/classification.py
verticapy/machine_learning/model_selection/variables_selection.py
verticapy/plotting/_plotly/__init__.py
verticapy/plotting/_plotly/outliers.py
verticapy/tests/vModel/test_model_selection.py

- Moving functions to the right category
- adding the right hints
- formatting the doc

CODE CLEANING: FORMATTING + TYPING + REORG

---

verticapy/plotting/_plotly/__init__.py
verticapy/plotting/_plotly/acf.py
verticapy/plotting/_plotly/base.py
verticapy/plotting/_plotly/boxplot.py
verticapy/tests/vDataFrame/test_vDF_plot_plotly.py

Plotly Integration - acf

---

verticapy/plotting/_plotly/__init__.py
verticapy/plotting/_plotly/machine_learning/__init__.py
verticapy/plotting/_plotly/machine_learning/elbow.py
verticapy/tests/vDataFrame/test_vDF_plot_plotly.py

- code for ML elbow curve
- unit test

Plotly ml elbow

---

verticapy/plotting/_plotly/__init__.py
verticapy/plotting/_plotly/machine_learning/__init__.py
verticapy/plotting/_plotly/machine_learning/regression.py
verticapy/tests/vDataFrame/test_vDF_plot_plotly.py

- regression code 
- unit test

plotly integration - ml regression plot

---

verticapy/plotting/_plotly/__init__.py
verticapy/plotting/_plotly/machine_learning/lof.py
verticapy/tests/vDataFrame/test_vDF_plot_plotly.py

- unit code for iof
- unit test

plotly integration - IOF plot

---

verticapy/_utils/_map.py
verticapy/_utils/_sql/_cast.py
verticapy/_utils/_sql/_check.py
verticapy/_utils/_sql/_format.py
verticapy/core/vdataframe/_aggregate.py
verticapy/core/vdataframe/_corr.py
verticapy/core/vdataframe/_eval.py
verticapy/core/vdataframe/_join_union_sort.py
verticapy/core/vdataframe/_machine_learning.py
verticapy/core/vdataframe/_pivot.py
verticapy/core/vdataframe/_sys.py
verticapy/core/vdataframe/_typing.py
verticapy/core/vdataframe/base.py
verticapy/jupyter/extensions/sql_magic.py
verticapy/machine_learning/metrics/regression.py
verticapy/machine_learning/vertica/model_management.py
verticapy/plotting/_plotly/machine_learning/lof.py
verticapy/plotting/base.py
verticapy/sql/dtypes.py

- Cleaning wrong init.
- startswith and endswith instead of ugly equalities.
TODO:
- except 
- warning and errors
=> end of code cleaning

CLEANING: Typing & Misc

---

verticapy/plotting/_plotly/__init__.py
verticapy/plotting/_plotly/machine_learning/pca.py
verticapy/tests/vDataFrame/test_vDF_plot_plotly.py

- pca circle plot
- unit tests
- made unit tests more efficient by fixing pytest fixtures

plotly integration - Pca circle plot

---

verticapy/plotting/_plotly/__init__.py
verticapy/plotting/_plotly/machine_learning/model_evaluation.py
verticapy/tests/vDataFrame/test_vDF_plot_plotly.py

- added ROC
- added PRC
- added cutoff_curve
- added lift_chart
Also 
- Unit tests for all above

Plotly Integration - ROC, PRC, CUT_OFF, LIFTCHART

---

verticapy/plotting/_plotly/__init__.py
verticapy/plotting/_plotly/machine_learning/kmeans.py
verticapy/tests/vDataFrame/test_vDF_plot_plotly.py

- added voronoi plot
- unit test

Plotly Integration - Voronoi plot

---

verticapy/tests_new/__init__.py
verticapy/tests_new/config/__init__.py
verticapy/tests_new/conftest.py
verticapy/tests_new/connection/__init__.py
verticapy/tests_new/core/parsers/__init__.py
verticapy/tests_new/core/string_sql/__init__.py
verticapy/tests_new/core/tablesample/__init__.py
verticapy/tests_new/core/vdataframe/__init__.py
verticapy/tests_new/datasets/__init__.py
verticapy/tests_new/jupyter/__init__.py
verticapy/tests_new/jupyter/extensions/__init__.py
verticapy/tests_new/machine_learning/__init__.py
verticapy/tests_new/machine_learning/memmodel/__init__.py
verticapy/tests_new/machine_learning/metrics/__init__.py
verticapy/tests_new/machine_learning/metrics/test_classification_metrics.py
verticapy/tests_new/machine_learning/model_selection/__init__.py
verticapy/tests_new/machine_learning/vertica/__init__.py
verticapy/tests_new/plotting/__init__.py
verticapy/tests_new/plotting/highcharts/__init__.py
verticapy/tests_new/plotting/matplotlib/__init__.py
verticapy/tests_new/plotting/plotly/__init__.py
verticapy/tests_new/sdk/__init__.py
verticapy/tests_new/sql/__init__.py
verticapy/tests_new/sql/functions/__init__.py
verticapy/tests_new/sql/geo/__init__.py
verticapy/tests_new/utils/__init__.py

- Creating the skeleton for the new unit tests to have a clean and robust structure.
- First UT for f1_score.

Unit Tests skeleton

---

verticapy/plotting/_plotly/__init__.py
verticapy/plotting/_plotly/machine_learning/regression_tree.py
verticapy/tests/vDataFrame/test_vDF_plot_plotly.py

- regression_tree plot
- unit test

Plotly ml regression tree

---

verticapy/plotting/_plotly/__init__.py
verticapy/plotting/_plotly/machine_learning/svm.py
verticapy/tests/vDataFrame/test_vDF_plot_plotly.py

Plotly Integration -ml svm plot

---

verticapy/machine_learning/model_selection/variables_selection.py

BUGFIX: Stepwise

---

verticapy/plotting/_plotly/__init__.py
verticapy/plotting/_plotly/machine_learning/champion_challenger.py
verticapy/tests/vDataFrame/test_vDF_plot_plotly.py

- plot
- -unit test (only basic)

Plotly ml champion challenger

---

verticapy/plotting/_plotly/__init__.py
verticapy/plotting/_plotly/machine_learning/stepwise.py
verticapy/tests/vDataFrame/test_vDF_plot_plotly.py

plotly integration - stepwise

---

verticapy/plotting/_plotly/__init__.py
verticapy/plotting/_plotly/hist.py
verticapy/tests/vDataFrame/test_vDF_plot_plotly.py

PLOTTING - Plotly Integration: Histogram

---

verticapy/_utils/_sql/_check.py

Including 'with' statement in the query checker

---

README.md

Adding a "conda-forge" badge in the README file

Update README.md with adding a "conda-forge" badge

---

CONTRIBUTING.md

Updates include:
- Removing previous syntax and deprecated examples
- Added new unit test details
- Added pylint and black details
close #613

Update contribute file

---

verticapy/tests_new/conftest.py
verticapy/tests_new/machine_learning/metrics/test_classification_metrics.py

PR for classification metrics.
Following tests are skipped as functions needs to be fixed for multi-class:
- best_cutoff
- roc_auc_score
- prc_auc_score
log_loss metrics is skipped as Vertica has default log base 10, whereas Sklearn has natural log (e)

619 unit testing classification metrics

---

verticapy/core/vdataframe/_encoding.py
verticapy/core/vdataframe/_plotting.py
verticapy/plotting/_plotly/__init__.py
verticapy/plotting/_plotly/bar.py
verticapy/plotting/base.py
verticapy/tests_new/plotting/base_test_files.py
verticapy/tests_new/plotting/plotly/test_plotly_bar.py

- added bar plot 2d for plotly

bar plot 2d for plotly

---

verticapy/core/vdataframe/_encoding.py
verticapy/core/vdataframe/_plotting.py
verticapy/plotting/_plotly/__init__.py
verticapy/plotting/_plotly/barh.py
verticapy/plotting/base.py
verticapy/tests_new/plotting/base_test_files.py
verticapy/tests_new/plotting/matplotlib/test_matplotlib_barh.py
verticapy/tests_new/plotting/plotly/test_plotly_barh.py

- plotting function
- unit tests

2D horizontal bar chart for plotly

---

verticapy/plotting/_highcharts/contour.py
verticapy/plotting/_plotly/contour.py

- Fixed Orientation of highcharts and plotly plot
- Fixed x-ticks and y-ticks for highcharts

Contour plot bug fix

---

verticapy/plotting/_highcharts/line.py

Fixed bug for multiple line plots using highcharts

bug fix - multi-line plot

---

verticapy/tests_new/conftest.py
verticapy/tests_new/machine_learning/vertica/linear_model/test_linear_regression.py

Unit test for linear-regression

633 unit testing linearregression

---

change_logs/change_log_v1.0.0-beta.md

- added classificaiton metric details
- added model name optional PR

Update change log

---

change_logs/change_log_v1.0.0-beta.md

Announcing addition of Model Tracking and Model Versioning into VerticaPy

Change log for MLOps

---

verticapy/datasets/generators.py

Proof of concept PR using small file (datasets.generators.py). (If this isn't the right place to merge, just let me know and I'll delete this PR and move it)

convert datasets/generators to rst

---

verticapy/tests_new/conftest.py
verticapy/tests_new/core/vdataframe/__init__.py
verticapy/tests_new/core/vdataframe/test_agg.py
verticapy/tests_new/core/vdataframe/test_correlation.py

aggregate and correlation UT code

aggregate and correlation UT code

---

verticapy/plotting/_plotly/bar.py
verticapy/plotting/_plotly/barh.py
verticapy/tests_new/plotting/plotly/test_plotly_bar.py
verticapy/tests_new/plotting/plotly/test_plotly_barh.py

Horizontal:
- stacked
- fully_stacked 
- negative (pyramid)
Bar
- stacked

Added Options for horizontal and vertical bar chart

---

verticapy/plotting/_plotly/hist.py
verticapy/tests_new/plotting/base_test_files.py
verticapy/tests_new/plotting/conftest.py
verticapy/tests_new/plotting/matplotlib/test_matplotlib_hist.py
verticapy/tests_new/plotting/plotly/test_plotly_hist.py

- multi-plot histogram for plotly
- unit tests for multiplot for matplotlib and plotly
- fixed conftest file to comply with pylint

added multi-plot functionalitt for plotly histogram plot

---

verticapy/plotting/_highcharts/__init__.py
verticapy/plotting/_highcharts/hist.py
verticapy/tests_new/plotting/highcharts/test_highcharts_hist.py

- hist plot for highcharts
- unit tests

highcharts histogram plot

---

verticapy/plotting/_highcharts/density.py

- fixed bug for the instance when there is no x_label (for multi-density)

Bugfix - Highcharts density plot

---

verticapy/plotting/_matplotlib/acf.py
verticapy/plotting/_matplotlib/bar.py
verticapy/plotting/_matplotlib/barh.py
verticapy/plotting/_matplotlib/boxplot.py
verticapy/plotting/_matplotlib/density.py
verticapy/plotting/_matplotlib/hist.py
verticapy/plotting/_matplotlib/line.py
verticapy/plotting/_matplotlib/outliers.py
verticapy/plotting/_matplotlib/pie.py
verticapy/plotting/_matplotlib/range.py
verticapy/plotting/_matplotlib/scatter.py
verticapy/plotting/_matplotlib/spider.py
verticapy/plotting/base.py

- Now all matplotlib plots accept "color" as well as  "colors" as parameters
- Boxplot and Pie can now change colors with user input

Color option added

---

verticapy/plotting/_plotly/pie.py

- fixed size and color both pie and nested pie chart in PLOTLY

Plotly Pie chart bug fix for size and color

---

verticapy/plotting/_matplotlib/scatter.py

fix color parameter/style_kwargs for category type plot for Matplotlib

matplotlib Scatter Plot for category - color bugfix

---

verticapy/plotting/_highcharts/pie.py

- fixes issue with Decimal outputs

Converted output to float

---

verticapy/plotting/_plotly/scatter.py

- fixed color option for scatter plot
- enabled bubble plot by size

scatter plot bug-fix and enhancement

---

verticapy/plotting/_plotly/range.py

- multiple plots available
- color change is very easy with colors=list option e.g. fig=data.range_plot(["col1","col2"],ts = "date", plot_median=True,
colors=["black","yellow"]
)

Plotly Range Plot Update

---

verticapy/plotting/_plotly/line.py

- added multi line
- added colors parameter

Plotly Line Plot Update

---

verticapy/plotting/_plotly/contour.py

Plotly Contour Plot - Color option

---

verticapy/plotting/_plotly/line.py
verticapy/tests/vDataFrame/test_vDF_plot_plotly.py
verticapy/tests_new/plotting/plotly/test_plotly_line.py

- added area, stacked, fully stack
- also fixed x axis label for line plot
- also unskipped the unit test

Plotly Area Plot

---

verticapy/plotting/_highcharts/acf.py

- now max is not 1 for viewing
- also colors can be changed

Highcharts ACF plot bugfix

---

verticapy/plotting/_matplotlib/__init__.py
verticapy/plotting/_matplotlib/candlestick.py
verticapy/tests_new/plotting/matplotlib/test_matplotlib_candlestick.py

Matplotlib Candlestick Plot Added

---

verticapy/plotting/_matplotlib/machine_learning/svm.py
verticapy/plotting/_plotly/machine_learning/svm.py

- Plotly
- Matplotlib
Now both allow color change

SVM Plot - Color option

---

verticapy/machine_learning/model_selection/hp_tuning/plotting.py

Added option to return the chart instead of the table. Useful for storing and modifying the plot.

Validation Curve - Return Chart Option

---

verticapy/machine_learning/memmodel/tree.py

Using render instead of view as view is causing issues.

Graphiz Tree Plot Bug FIx

---

verticapy/plotting/_highcharts/acf.py
verticapy/plotting/_plotly/acf.py

- Fixed max and min for highcharts plot to 1.2 instead of 1 previously
- Changed default color for Plotly

ACF Plot - minor changes

---

verticapy/machine_learning/model_selection/hp_tuning/plotting.py

Validation Curve Plot - renaming return_chart to show

---

verticapy/plotting/_plotly/machine_learning/kmeans.py
verticapy/tests/vModel/test_iforest.py

Added option for Voronoi plot to select colors using "colors" parameter.
+ Skipped iforest test which was being buggy. Need to investigate

Plotly voronoi colors

---

verticapy/plotting/_plotly/machine_learning/lof.py
verticapy/tests/vModel/test_iforest.py

- FIxed bug for 3D plot
- Added colors option

PLotly LOF bugfix

---

verticapy/connection/connect.py
verticapy/connection/external.py
verticapy/connection/read.py
verticapy/connection/utils.py
verticapy/connection/write.py

Converts the files in the connection module. These conversions were pretty straightforward. I hard-coded the outputs for some examples because they had passwords in the output.

sphinx conversion connection directory

---

verticapy/jupyter/extensions/chart_magic.py
verticapy/jupyter/extensions/sql_magic.py
verticapy/machine_learning/memmodel/tree.py

I was able to convert the SQL magic page, but the hchart extension wouldn't load. Any ideas? Kept getting this error:
`UsageError: Line magic function `%hchart` not found.`

sphinx conversion -- sql magic

---

verticapy/tests_new/conftest.py
verticapy/tests_new/core/vdataframe/test_text.py
verticapy/tests_new/core/vdataframe/test_typing.py

UT for vDataFrame - typing and text

UT for vDataFrame - typing and text

---

verticapy/core/vdataframe/_aggregate.py
verticapy/tests/vDataFrame/test_vDF_descriptive_statistics.py

Docstring for verticapy.core.vDataFrame._aggregate:
Missing docstring for:
- def describe (vdf & vdc)
Main reviewer: @mail4umar 
@tconsigny please double check **if you get the chance**.

SPHINX - verticapy.core.vDataFrame._aggregate

---

verticapy/core/vdataframe/_aggregate.py
verticapy/core/vdataframe/_corr.py

@mail4umar can you please correct corr so I can do the others, they will follow the same template.
@tconsigny please review if you have time.

SPHINX: describe + corr

---

verticapy/machine_learning/vertica/linear_model.py

Completed all linear models.
Also made a draft for first classification model. @oualib please provide your feedback on it.

Sphinx machine learning/vertica/linear model

---

verticapy/machine_learning/memmodel/naive_bayes.py
verticapy/plotting/_matplotlib/candlestick.py

Color option was not working for list inputs.

Bugfix - Matplotlib - Candlestick Plot

---

verticapy/machine_learning/metrics/classification.py

- making clearer the error message of auc/prc auc

making clearer auc, prc

---

verticapy/machine_learning/vertica/base.py

Improving the model summary - fit

---

verticapy/machine_learning/metrics/regression.py

Todo: 
- Anova Table
- Regression Report
- Quantile Error

Sphinx Docstring Regression Metrics

---

verticapy/_utils/_sql/_vertica_version.py
verticapy/machine_learning/vertica/__init__.py
verticapy/machine_learning/vertica/linear_model.py

- Supporting Vertica Poisson Regression
@vikash018 please do a PR for PoissonReg Unit Tests.
@mail4umar please review the PR and comment.

PoissonRegressor

---

verticapy/core/vdataframe/_filter.py

New parameter:
force_filter: bool, optional
Default Value: True
When set to True, the vDataFrame will be modified
even if no filtering occurred. This parameter can
be used to enforce filtering  and ensure pipeline
consistency.
raise_error: bool, optional
Default Value: False
If set to True and the input filtering is incorrect,
an error is raised.
It makes the function much more consistent and keep the pipeline logical.

Making the "filter" method more consistent.

---

verticapy/machine_learning/metrics/__init__.py
verticapy/machine_learning/metrics/classification.py

Need to understand why classification_report is not working @oualib can you please help

Sphinx Docstring Metrics for Classification

---

verticapy/machine_learning/vertica/automl/supervised.py

- added an error with a clear message.

Correcting AutoML bug

---

verticapy/_config/config.py
verticapy/_config/validators.py
verticapy/_utils/_sql/_format.py
verticapy/_utils/_sql/_sys.py

New options to set option:
- label_separator
- label_suffix

Adding the possibility to customise query labels

---

verticapy/machine_learning/metrics/classification.py

- can now handle custom probas for multiclass

Improving classification report

---

verticapy/tests_new/machine_learning/vertica/__init__.py
verticapy/tests_new/machine_learning/vertica/conftest.py
verticapy/tests_new/machine_learning/vertica/test_base_model_methods.py
verticapy/tests_new/machine_learning/vertica/test_linear_model.py

PoissonRegressor UT

---

verticapy/core/vdataframe/_io.py
verticapy/core/vdataframe/_sys.py

Adding parameters to to_db function

---

verticapy/machine_learning/model_selection/statistical_tests/norm.py
verticapy/machine_learning/model_selection/statistical_tests/ols.py
verticapy/machine_learning/model_selection/statistical_tests/tsa.py

@oualib please have a look at the basic examples. I will copy these for other functions.

Sphinx Docstring - model selection - basic examples

---

verticapy/_utils/_sql/_vertica_version.py
verticapy/machine_learning/vertica/__init__.py
verticapy/machine_learning/vertica/base.py
verticapy/machine_learning/vertica/model_management.py
verticapy/machine_learning/vertica/pmml.py

- export_models
- import_models
- to_pmml
- to_tensorflow
- to_binary
- PMMLModel class
TODO next:
- support PMML in load_model
- check in the PMML init

Model IMPORT/EXPORT + PMML Support

---

verticapy/_utils/_sql/_vertica_version.py
verticapy/machine_learning/vertica/__init__.py
verticapy/machine_learning/vertica/base.py
verticapy/machine_learning/vertica/model_management.py
verticapy/machine_learning/vertica/tensorflow.py
verticapy/tests/vModel/test_tools.py
verticapy/tests_new/machine_learning/vertica/test_base_model_methods.py

- TF object
- improvement of PMML
- load_model support for PMML and TF
- more precise docstring

PMML and TF INTEGRATION

---

verticapy/tests_new/conftest.py
verticapy/tests_new/machine_learning/vertica/__init__.py
verticapy/tests_new/machine_learning/vertica/conftest.py
verticapy/tests_new/machine_learning/vertica/test_base_model_methods.py
verticapy/tests_new/machine_learning/vertica/test_linear_model.py
verticapy/tests_new/machine_learning/vertica/test_tree_model.py

autoregressor unit test code

---

docs/reverse_replace_sphinx_dir.py
verticapy/machine_learning/vertica/tsa.py

Made two sections: 
- one-step ahead forecasting
- full forecasting
Also fixed error in reverse SPHINX_DIRECTORY script

Docstring Update for TSA

---

docs/source/machine_learning_vertica_decomposition.rst
verticapy/_utils/_sql/_vertica_version.py
verticapy/learn/preprocessing/__init__.py
verticapy/machine_learning/vertica/__init__.py
verticapy/machine_learning/vertica/cluster.py
verticapy/machine_learning/vertica/ensemble.py
verticapy/machine_learning/vertica/linear_model.py
verticapy/machine_learning/vertica/naive_bayes.py
verticapy/machine_learning/vertica/neighbors.py
verticapy/machine_learning/vertica/preprocessing.py
verticapy/machine_learning/vertica/svm.py
verticapy/machine_learning/vertica/tree.py
verticapy/tests/vModel/test_balance.py

- Balance -> balance (it is not a class but a function)
- docstring to explain what to do.
- formatting.

Correcting balance function and adding docstrings

---

verticapy/machine_learning/model_selection/statistical_tests/norm.py

Added docstring of other norm functions

Sphinx - model selection / statistical tests - 2

---

verticapy/machine_learning/vertica/feature_extraction/text.py

- improve code quality.
- Use RST to build up an example.
- Unify variable names.
- Add parameter to control normalization (at the moment only L2)
- Add parameter for smoothing (at the moment is always applied)
- Rewrite part of the queries to make them more readable

Improve TF-IDF

---

verticapy/machine_learning/vertica/feature_extraction/text.py

- Adding new parameters
- New attributes
- correcting overall formatting

TF IDF - Improvement 2

---

verticapy/machine_learning/vertica/tsa.py
verticapy/plotting/_highcharts/machine_learning/tsa.py
verticapy/plotting/_matplotlib/machine_learning/tsa.py
verticapy/plotting/_plotly/machine_learning/tsa.py

- features importance x100
- plot always have the same color.

Making TS Plots and FI consistent

---

docs/source/stats.rst
verticapy/machine_learning/model_selection/statistical_tests/tsa.py

All statistical functions except seasonal_decompose.

Sphinx Docstring - model selection / statistical tests / tsa

---

verticapy/performance/__init__.py
verticapy/performance/vertica/__init__.py
verticapy/performance/vertica/qprof.py

- Creating the object
- Supporting 3 steps.

Query Profile v0

---

verticapy/_utils/_sql/_display.py
verticapy/_utils/_sql/_format.py
verticapy/core/parsers/all.py
verticapy/core/parsers/csv.py
verticapy/core/parsers/json.py
verticapy/core/parsers/shp.py
verticapy/core/vdataframe/_encoding.py
verticapy/core/vdataframe/_sys.py
verticapy/datasets/loaders.py
verticapy/datasets/tests_loaders.py
verticapy/machine_learning/vertica/base.py
verticapy/sql/drop.py
verticapy/sql/dtypes.py
verticapy/sql/insert.py

1. Starting a real query formatter
2. changing the public schema by the temp_schema
3. Some code formatting

Multiple corrections - Formatter + temp_schema

---

verticapy/machine_learning/vertica/feature_extraction/text.py

- doc string update: added more detail
- close #883

Sphinx Docstring Update + bugfix for TFIDF

---

verticapy/performance/vertica/qprof.py
verticapy/plotting/base.py

- Adding more methods
- Doing the doc

Improving QPROF

---

docs/source/_static/css/custom_styling.css
docs/source/conf.py
docs/source/user_guide.rst
docs/source/user_guide_data_exploration.rst
docs/source/user_guide_data_preparation.rst
docs/source/user_guide_full_stack.rst
docs/source/user_guide_introduction.rst
docs/source/user_guide_machine_learning.rst

- Canged the RST pages for User Guide
- Updated CSS style for userguide pages
- Updated Style for entire doc
- - Entire doc has two headers

Sphinx rst files

---

verticapy/core/vdataframe/_plotting_animated.py

Added docstring examples for animated plots

Sphinx Docstring - core/vdataframe/animated_plots

---

verticapy/core/vdataframe/_fill.py
verticapy/core/vdataframe/_filter.py

Docstring
- _filter.py
- _fill.py

Sphinx Docstring Core / vdataframe /  fill + filter

---

docs/source/utilities.rst
verticapy/core/vdataframe/_plotting_animated.py
verticapy/core/vdataframe/_scaler.py
verticapy/core/vdataframe/_text.py
verticapy/core/vdataframe/_utils.py
verticapy/machine_learning/memmodel/ensemble.py
verticapy/machine_learning/memmodel/preprocessing.py
verticapy/machine_learning/memmodel/tree.py
verticapy/machine_learning/vertica/preprocessing.py
verticapy/sql/functions/regexp.py
verticapy/sql/geo/functions.py
verticapy/sql/geo/index.py

Also minor:
- Added "okwarning" in docstring for regexp functions

Sphinx RST File Modification - Added QueryProfiler

---

docs/source/vdataframe.rst
verticapy/core/vdataframe/_filter.py
verticapy/core/vdataframe/_sys.py
verticapy/core/vdataframe/_text.py
verticapy/machine_learning/vertica/cluster.py
verticapy/machine_learning/vertica/neighbors.py

- also updated rst file for missing functions
close #912

Sphinx Docstring vdataframe/_sys

---

verticapy/core/vdataframe/_math.py

- Added docstring for all functions inside _math.py
close #908

Sphinx Docstring core / vdataframe / _math

---

verticapy/core/vdataframe/_pivot.py

- Docstring for all functions inside Pivot
@oualib Can you please help me complete the flatten_vmap example.
close #909

Sphinx Docstring core / vdataframe / _pivot

---

verticapy/core/vdataframe/_rolling.py

- all functions for _rolling,py
close #911

Sphinx Docstring for core / vdataframe / _rolling functions

---

verticapy/core/vdataframe/_join_union_sort.py
verticapy/core/vdataframe/_sys.py

Added sections for:
- INNER JOIN
- LEFT
- RIGHT
- FULL
- Other operators
close #941 
Also:
- Added verticapy import for one _sys function

Sphinx Docstring - Enhanced docstrings for JOIN

---

verticapy/core/vdataframe/_read.py

All functions inside the _read.py file

Sphinx Docstring - core / vdataframe / _read

---

docs/source/error.rst
verticapy/errors/__init__.py
verticapy/sql/geo/functions.py
verticapy/sql/geo/index.py

Correcting geo.
Creating the error docstrings.

Multiple docstrings

---

docs/source/contribution_guidelines_code_auto_doc_example.rst
docs/source/user_guide.rst
docs/source/user_guide_introduction.rst
docs/source/whats_new_v1_0_0.rst
verticapy/_config/config.py
verticapy/_config/validators.py
verticapy/core/string_sql/base.py
verticapy/core/vdataframe/_join_union_sort.py
verticapy/core/vdataframe/_math.py
verticapy/core/vdataframe/_pivot.py
verticapy/core/vdataframe/_read.py
verticapy/core/vdataframe/_rolling.py
verticapy/core/vdataframe/_sys.py
verticapy/core/vdataframe/_utils.py
verticapy/core/vdataframe/base.py
verticapy/sql/geo/functions.py
verticapy/sql/geo/index.py

New docstrings: StringSQL, config, validators.
Corrections: using right references for vdf, vdc, tablesamples.

Multiple docstrings + correction

---

verticapy/core/vdataframe/_machine_learning.py

All functions for the _machine_learning.py file
close #907

Sphinx Docstring core vdataframe / machine learning

---

verticapy/core/vdataframe/_io.py

Sphinx docstring changes for vdataframe/io

---

verticapy/machine_learning/memmodel/base.py
verticapy/machine_learning/memmodel/cluster.py
verticapy/machine_learning/memmodel/decomposition.py
verticapy/machine_learning/memmodel/ensemble.py
verticapy/machine_learning/memmodel/linear_model.py
verticapy/machine_learning/memmodel/naive_bayes.py
verticapy/machine_learning/memmodel/preprocessing.py
verticapy/machine_learning/memmodel/tree.py

Missing: tree and ensemble - will be done in another PR

[Docstring] Memmodel - PART 1

---

verticapy/core/vdataframe/_machine_learning.py
verticapy/machine_learning/model_selection/kmeans.py
verticapy/machine_learning/vertica/cluster.py
verticapy/machine_learning/vertica/decomposition.py
verticapy/machine_learning/vertica/ensemble.py
verticapy/machine_learning/vertica/feature_extraction/text.py
verticapy/machine_learning/vertica/linear_model.py
verticapy/machine_learning/vertica/naive_bayes.py
verticapy/machine_learning/vertica/neighbors.py
verticapy/machine_learning/vertica/preprocessing.py
verticapy/machine_learning/vertica/svm.py
verticapy/machine_learning/vertica/tree.py
verticapy/machine_learning/vertica/tsa.py
verticapy/sql/flex.py
verticapy/sql/functions/regexp.py
verticapy/sql/geo/functions.py
verticapy/sql/geo/index.py
verticapy/sql/insert.py

- kmeans docstring
- misc to make the formatting better

[Docstring] kmeans + misc

---

verticapy/core/vdataframe/_pivot.py
verticapy/machine_learning/memmodel/cluster.py
verticapy/machine_learning/memmodel/ensemble.py
verticapy/machine_learning/memmodel/tree.py
verticapy/machine_learning/model_selection/model_validation.py
verticapy/machine_learning/vertica/automl/clustering.py
verticapy/machine_learning/vertica/base.py
verticapy/machine_learning/vertica/cluster.py
verticapy/machine_learning/vertica/svm.py

[Docstring] Memmodel + Misc

---

verticapy/core/vdataframe/_machine_learning.py
verticapy/core/vdataframe/_pivot.py
verticapy/machine_learning/metrics/regression.py
verticapy/machine_learning/model_selection/hp_tuning/cv.py
verticapy/machine_learning/model_selection/model_validation.py
verticapy/machine_learning/model_selection/variables_selection.py
verticapy/machine_learning/vertica/automl/clustering.py
verticapy/machine_learning/vertica/base.py
verticapy/machine_learning/vertica/cluster.py
verticapy/machine_learning/vertica/svm.py

- Also corrected model_validation

Sphinx Docstring for hp_tuning/cv 

---

verticapy/machine_learning/model_selection/hp_tuning/cv.py
verticapy/machine_learning/model_selection/model_validation.py
verticapy/machine_learning/vertica/automl/dataprep.py
verticapy/machine_learning/vertica/automl/supervised.py
verticapy/machine_learning/vertica/cluster.py
verticapy/machine_learning/vertica/decomposition.py
verticapy/machine_learning/vertica/ensemble.py
verticapy/machine_learning/vertica/feature_extraction/text.py
verticapy/machine_learning/vertica/linear_model.py
verticapy/machine_learning/vertica/naive_bayes.py
verticapy/machine_learning/vertica/neighbors.py
verticapy/machine_learning/vertica/preprocessing.py
verticapy/machine_learning/vertica/svm.py
verticapy/machine_learning/vertica/tree.py
verticapy/machine_learning/vertica/tsa.py

Docstring for model_validation
Misc correction for vertica models docstrings

[Docstring] model_validation + misc

---

verticapy/machine_learning/vertica/automl/supervised.py
verticapy/machine_learning/vertica/base.py
verticapy/machine_learning/vertica/cluster.py
verticapy/machine_learning/vertica/decomposition.py
verticapy/machine_learning/vertica/ensemble.py
verticapy/machine_learning/vertica/linear_model.py
verticapy/machine_learning/vertica/neighbors.py
verticapy/machine_learning/vertica/preprocessing.py
verticapy/machine_learning/vertica/svm.py
verticapy/machine_learning/vertica/tsa.py

Created very brief examples for the different functions inside the base class.
closes #980

Sphinx Docstring - Added examples for functions inside decomposition.py

---

verticapy/core/parsers/pandas.py
verticapy/core/vdataframe/base.py
verticapy/datasets/generators.py
verticapy/machine_learning/metrics/classification.py
verticapy/machine_learning/metrics/regression.py
verticapy/machine_learning/model_selection/hp_tuning/cv.py
verticapy/machine_learning/model_selection/hp_tuning/plotting.py
verticapy/machine_learning/model_selection/model_validation.py
verticapy/machine_learning/model_selection/statistical_tests/norm.py
verticapy/machine_learning/model_selection/statistical_tests/ols.py
verticapy/machine_learning/model_selection/statistical_tests/tsa.py
verticapy/machine_learning/model_selection/variables_selection.py
verticapy/machine_learning/vertica/cluster.py
verticapy/machine_learning/vertica/decomposition.py
verticapy/machine_learning/vertica/ensemble.py
verticapy/machine_learning/vertica/linear_model.py
verticapy/machine_learning/vertica/naive_bayes.py
verticapy/machine_learning/vertica/neighbors.py
verticapy/machine_learning/vertica/svm.py
verticapy/machine_learning/vertica/tree.py
verticapy/machine_learning/vertica/tsa.py

- linear_models docstrings
- misc formatting

Docstrings for linear_models + misc

---

verticapy/machine_learning/metrics/regression.py
verticapy/machine_learning/vertica/base.py
verticapy/machine_learning/vertica/tsa.py

Docstring for Time Series.

---

verticapy/machine_learning/vertica/cluster.py
verticapy/machine_learning/vertica/ensemble.py
verticapy/machine_learning/vertica/linear_model.py
verticapy/machine_learning/vertica/preprocessing.py

- docstrings for methods in the file.

[Docstring] vertica/preprocessing

---

verticapy/core/parsers/_utils.py
verticapy/core/parsers/json.py
verticapy/core/vdataframe/_machine_learning.py
verticapy/machine_learning/vertica/base.py
verticapy/machine_learning/vertica/linear_model.py
verticapy/machine_learning/vertica/model_management.py
verticapy/machine_learning/vertica/neighbors.py
verticapy/machine_learning/vertica/svm.py

[Docstring] VerticaModel + Regression + Unsupervised + MISC

[Docstring] VerticaModel + Regression + Unsupervised

---

verticapy/core/parsers/csv.py
verticapy/core/parsers/json.py

- adding example for injesting multiple csv and cleanup code in parsers/csv
- adding example for injesting multiple json in parsers/json

Sphinx docstring corrections for parsers/csv and json

---

verticapy/machine_learning/vertica/base.py

Sphinx Docstring machine_learning / vertica / base

---

verticapy/core/parsers/csv.py
verticapy/core/parsers/json.py
verticapy/machine_learning/vertica/base.py
verticapy/machine_learning/vertica/ensemble.py
verticapy/machine_learning/vertica/linear_model.py

- vertica/base docstring
- corrections: misc

Finalising vertica/base docstrings

---

verticapy/machine_learning/vertica/cluster.py
verticapy/machine_learning/vertica/neighbors.py

Final docstring for ML.

---

docs/source/_static/css/custom_styling.css

Sphinx Style update - version boxes style changed

---

verticapy/connection/connect.py
verticapy/connection/external.py
verticapy/connection/global_connection.py
verticapy/connection/read.py
verticapy/connection/utils.py
verticapy/connection/write.py
verticapy/core/parsers/all.py
verticapy/core/parsers/avro.py
verticapy/core/parsers/csv.py
verticapy/core/parsers/json.py
verticapy/core/parsers/pandas.py
verticapy/core/parsers/shp.py
verticapy/sql/geo/functions.py
verticapy/sql/geo/index.py

- finalizing parsers.
- misc corrections.

Ending docstrings - iter 1

---

verticapy/__init__.py
verticapy/core/vdataframe/_aggregate.py
verticapy/core/vdataframe/_read.py
verticapy/core/vdataframe/base.py
verticapy/jupyter/extensions/sql_magic.py
verticapy/performance/vertica/qprof.py

Multiple bug corrections

---

verticapy/core/vdataframe/_plotting.py
verticapy/performance/vertica/qprof.py
verticapy/plotting/base.py

- categoryorder support
- more options for graphics
- docstrings

QPROF Improvements

---

verticapy/__init__.py
verticapy/performance/vertica/qprof.py
verticapy/plotting/_plotly/subplots.py
verticapy/plotting/base.py

v_schema_names -> target_schema
v_table_names -> target_table
new params

QPROF improvement

---

verticapy/__init__.py
verticapy/_utils/_inspect_statistics.py
verticapy/core/vdataframe/_plotting.py
verticapy/performance/vertica/tree.py
verticapy/plotting/_plotly/subplots.py

- correcting the tree.
- using default argument for the plots.

QPROF - Tree Correction

---

verticapy/__init__.py
verticapy/performance/vertica/qprof.py
verticapy/performance/vertica/tree.py
verticapy/plotting/_plotly/subplots.py

Finalizing trees
misc corrections

QPROF Tree Improvement + misc

---

verticapy/tests_new/conftest.py
verticapy/tests_new/core/vdataframe/test_join_union_sort.py
verticapy/tests_new/core/vdataframe/test_machine_learning.py
verticapy/tests_new/core/vdataframe/test_pivot.py

UT for machine learning, join union sort  and pivot files.

778 tests vdataframe machine learning + join union sort + pivot

---

verticapy/__init__.py
verticapy/_utils/_inspect_statistics.py
verticapy/performance/vertica/qprof.py

Query Profiler - create_table correction.

---

verticapy/core/tablesample/base.py
verticapy/datasets/generators.py
verticapy/machine_learning/memmodel/linear_model.py
verticapy/machine_learning/model_selection/hp_tuning/plotting.py

Just a few small bugs that were causing issues compiling using sphinx.

Sphinx - Fixed doc string bugs

---

docs/requirements.txt
docs/source/conf.py
verticapy/_utils/_display.py
verticapy/core/vdataframe/_machine_learning.py
verticapy/machine_learning/memmodel/cluster.py
verticapy/machine_learning/memmodel/ensemble.py
verticapy/machine_learning/memmodel/tree.py
verticapy/machine_learning/vertica/base.py
verticapy/machine_learning/vertica/cluster.py
verticapy/machine_learning/vertica/ensemble.py
verticapy/machine_learning/vertica/tree.py
verticapy/performance/vertica/qprof.py

- copy code button.
- graphviz instead of png.

New RST improvement

---

docs/source/_static/css/custom_styling.css
docs/source/api.rst
docs/source/chart_gallery.rst
docs/source/cicd_black.rst
docs/source/connectors.rst
docs/source/getting_started.rst
docs/source/index.rst
docs/source/installation.rst
docs/source/machine_learning_vertica_classification.rst
docs/source/machine_learning_vertica_clustering.rst
docs/source/machine_learning_vertica_decomposition.rst
docs/source/machine_learning_vertica_text.rst
docs/source/machine_learning_vertica_time_series.rst
docs/source/performance.rst
docs/source/tablesample.rst
docs/source/user_guide_data_exploration.rst
docs/source/user_guide_data_preparation.rst
docs/source/user_guide_introduction.rst
docs/source/user_guide_machine_learning.rst
docs/source/utilities.rst
docs/source/whats_new_v1_0_0.rst
verticapy/core/tablesample/base.py
verticapy/machine_learning/vertica/preprocessing.py

- changing look and feel
- correcting bugs

[Sphinx] RST Changes

---

verticapy/__init__.py
verticapy/performance/vertica/qprof.py
verticapy/performance/vertica/tree.py

- new metrics
- possibility to display more information

[QPROF] Supporting more elements

---

docs/source/conf.py
docs/source/getting_started.rst
docs/source/index.rst
docs/source/installation.rst
docs/source/notebooks/introduction/installation/index.ipynb
verticapy/__init__.py
verticapy/_help.py
verticapy/jupyter/extensions/sql_magic.py
verticapy/machine_learning/vertica/cluster.py
verticapy/machine_learning/vertica/decomposition.py
verticapy/machine_learning/vertica/ensemble.py
verticapy/machine_learning/vertica/linear_model.py
verticapy/machine_learning/vertica/naive_bayes.py
verticapy/machine_learning/vertica/neighbors.py
verticapy/machine_learning/vertica/preprocessing.py
verticapy/machine_learning/vertica/svm.py
verticapy/machine_learning/vertica/tree.py
verticapy/machine_learning/vertica/tsa.py
verticapy/performance/vertica/tree.py

- Qprof bug fix
- doc link fix

Doc + QPROF Improvements

---

verticapy/__init__.py
verticapy/performance/vertica/qprof.py
verticapy/performance/vertica/tree.py

- Possibility to add two legends
- Projection info
- Bug fixing (trim)

[QPROF] 2 LEGENDS + PROJ + BUG

---

verticapy/__init__.py
verticapy/_config/config.py
verticapy/_utils/_display.py
verticapy/plotting/_plotly/bar.py
verticapy/plotting/_plotly/base.py

- Adding dark/light/sphinx modes.

VerticaPy Themes

---

verticapy/performance/vertica/qprof.py

Sphinx - Docstring - Small Fix

---

docs/source/benchmarks_arima.rst
docs/source/benchmarks_linear_reg.rst
docs/source/benchmarks_logistic_reg.rst
docs/source/benchmarks_naive.rst
docs/source/benchmarks_random_forest.rst
docs/source/benchmarks_xgboost.rst

- Consistent environment details i.e. Memory and vCPU
- Added missing versions

Sphinx RST Pages - Updated Benchmarks

---

verticapy/_utils/_display.py
verticapy/performance/vertica/qprof.py
verticapy/performance/vertica/tree.py

- Correcting a bug on display tables.
- Improving QPROF experience with new functionalities.
- Using Key ID instead of statement_id and transaction_id.
- Supporting INSERT.

[QPROF] Key ID

---

docs/create_toc_tree.py
docs/source/_static/css/custom_styling.css
docs/source/chart_gallery_tree.rst
docs/source/cicd_codecov.rst
requirements-dev.txt
requirements-testing.txt
verticapy/__init__.py
verticapy/machine_learning/memmodel/cluster.py
verticapy/machine_learning/memmodel/tree.py
verticapy/machine_learning/vertica/base.py
verticapy/machine_learning/vertica/cluster.py
verticapy/performance/vertica/qprof.py
verticapy/performance/vertica/tree.py
verticapy/plotting/_plotly/bar.py
verticapy/plotting/base.py
verticapy/tests/vModel/test_bisecting_kmeans.py
verticapy/tests/vModel/test_dummy_tree_classifier.py
verticapy/tests/vModel/test_dummy_tree_regressor.py
verticapy/tests/vModel/test_iforest.py
verticapy/tests/vModel/test_xgb_classifier.py
verticapy/tests_new/machine_learning/vertica/test_tree_model.py

- Adding Dark Mode for tree.
- Correcting QPROF object.
- Correcting the doc rendering.

[SPHINX + PLOTTING + QPROF] Misc

---

verticapy/__init__.py
verticapy/performance/vertica/qprof.py

- qdurations are stored
- two new functions: set_position and get_transactions to navigate and understand all the queries.

[QPROF] Navigation

---

verticapy/__init__.py
verticapy/core/vdataframe/_read.py
verticapy/performance/vertica/qprof.py

- bug on duration
- changing the name get_transactions to get_queries
- adding appropriate error messages.

[QPROF] Bug correction

---

docs/source/performance_vertica.rst
verticapy/_utils/_sql/_sys.py
verticapy/core/tablesample/base.py
verticapy/core/vdataframe/_read.py
verticapy/core/vdataframe/base.py
verticapy/performance/vertica/qprof.py

- correcting some bugs on labels and queries.
- consistent warning message.

[QPROF] Improving Warnings + BUG correction

---

README.md

Updated README 
- Added GIFs instead of static pics
- Added "Theme" section

Update readme - Added GIFs + Themes

---

docs/source/_static/css/custom_styling.css
docs/source/chart_gallery_seasonal.rst
verticapy/performance/vertica/qprof.py

- Docstring correction for qprof
- RST File correction for Seasonal plots
- CSS adjustments
Also corrected a Value Error bug.

Sphinx Compiling Corrections + Minor Bug

---

docs/remove_pattern.py
docs/source/_static/css/custom_styling.css
docs/source/index.rst

- Increased font sizes
- Updated script to remove unnecessary text in code blocks

Sphinx font size increase + script update

---

README.md
docs/source/whats_new_v1_0_1.rst

- added link for the newsletter

Update Readme + What's New

---

verticapy/tests_new/machine_learning/metrics/test_classification_metrics.py

added tolerance for type dictionary results.

added tolerance for dict results

---

verticapy/tests_new/machine_learning/vertica/test_linear_model.py
verticapy/tests_new/machine_learning/vertica/test_tree_model.py

added code to generate error report for linear regression and tree models.

added code to generate error report for lr and tree models

---

verticapy/jupyter/_widgets.py
verticapy/jupyter/html/__init__.py
verticapy/jupyter/html/index.html
verticapy/performance/vertica/qprof_interface.py
verticapy/performance/vertica/qprof_utility.py
verticapy/performance/vertica/tree.py

This defines the new QueryProfileInterface.

Add QueryProfilerInterface

---

verticapy/tests_new/machine_learning/memmodel/test_cluster.py
verticapy/tests_new/machine_learning/memmodel/test_ensemble.py
verticapy/tests_new/machine_learning/memmodel/test_tree.py

updated memmodel.cluster with NearestCentroid unit tests
added memmodel.tree and memmodel.ensemble unit tests

Unit test for memmodel.tree and memmodel.ensemble

---

verticapy/plotting/_plotly/__init__.py
verticapy/plotting/_plotly/machine_learning/pca.py
verticapy/tests_new/plotting/base_test_files.py
verticapy/tests_new/plotting/highcharts/machine_learning/test_highcharts_pca.py
verticapy/tests_new/plotting/plotly/machine_learning/test_plotly_pca.py

- Added plotly Scree plot
- Added Var plot
Unit tests:
- Plotly Scree
- Plotly Var
- Highcharts Scree
- Highcarts Var
close #994

Added Plotly Plot for Scree and Var

---

verticapy/performance/vertica/qprof.py
verticapy/performance/vertica/tree.py

- broken pipe
- loading bar
- wrong display
- weird warnings

Correcting all QPROF bug

---

docs/source/pipeline.rst
verticapy/pipeline/_helper.py
verticapy/pipeline/_ingest.py
verticapy/pipeline/_schedule.py
verticapy/pipeline/_train.py
verticapy/pipeline/_transform.py
verticapy/pipeline/_validate.py
verticapy/pipeline/parser.py

Improved Pipeline Documentation

---

docs/source/contribution_guidelines.rst
docs/source/tolerance.rst

Added the tolerance page for difference ML algorithms. 
https://github.com/vertica/VerticaPy/assets/46414488/a5585f0d-9cd7-4f65-b80c-63b2bdab3188

Sphinx - tolerance page addition

---

verticapy/performance/vertica/qprof_interface.py
verticapy/performance/vertica/qprof_utility.py
verticapy/tests_new/performance/vertica/test_qprof.py

- _get_metric_name was not working correctly with inv = True. Fixed that.
- Added more readable tags for metrics for the QueryProfilerInterface

QueryProfielrInterface - Added more readable tags for Interface + Fixed _get_metric_name.

---

verticapy/machine_learning/vertica/tsa/base.py
verticapy/machine_learning/vertica/tsa/ensemble.py

- features_importance
- plot
- ...

[TimeSeriesByCategory] Adding the other functions.

---

docs/source/machine_learning_vertica_time_series.rst
docs/source/whats_new_v1_0_2.rst
setup.py
verticapy/__init__.py
verticapy/machine_learning/vertica/tsa/ensemble.py

- Added new page for whats new v1.0.2 in the doc
- Updated TimeSeries RST page to include the new class: TimeSeriesByCategory
- Updated docstring for the class: TimeSeriesByCategory

Doc Update  - whats new v1.0.2 + TimeSeriesByCategory

---

.github/workflows/ci.yaml
requirements-testing.txt
tox.ini
verticapy/performance/vertica/qprof.py
verticapy/performance/vertica/qprof_interface.py
verticapy/tests_new/machine_learning/vertica/test_model_management.py

Following changes:
- Query information to be not in one line
- Target_schema - only give me the name of the schema
- Added a parameter to avoid unnecessary initialization while importing.

Qprof modifications

---

verticapy/performance/vertica/qprof.py
verticapy/performance/vertica/qprof_interface.py
verticapy/performance/vertica/tree.py

- Fix bug for no schema
- Update formatting for display

Update look + fix bug

---

verticapy/performance/vertica/tree.py

Adding the option to use or not use temprel

QPROF - TEMPREL

---

verticapy/_utils/_sql/_vertica_version.py
verticapy/machine_learning/vertica/__init__.py
verticapy/machine_learning/vertica/model_management.py
verticapy/machine_learning/vertica/tsa/__init__.py
verticapy/machine_learning/vertica/tsa/arima.py
verticapy/machine_learning/vertica/tsa/base.py
verticapy/plotting/base.py
verticapy/tests_new/machine_learning/vertica/test_base_model_methods.py

Adding VAR to VerticaPy

---

verticapy/performance/vertica/qprof_interface.py

Now users can switch between temprel view and comprehensive view that have one big table

QprofInterface - Added button to switch temp_rel view

---

.github/workflows/pylint.yml
verticapy/_config/config.py
verticapy/_help.py
verticapy/_utils/_display.py
verticapy/_utils/_parsers.py
verticapy/core/vdataframe/_corr.py
verticapy/core/vdataframe/_io.py
verticapy/core/vdataframe/_rolling.py
verticapy/core/vdataframe/_typing.py
verticapy/jupyter/_javascript.py
verticapy/jupyter/extensions/sql_magic.py
verticapy/machine_learning/vertica/automl/dataprep.py
verticapy/performance/vertica/qprof.py
verticapy/plotting/_matplotlib/animated/bubble.py
verticapy/plotting/_matplotlib/scatter.py
verticapy/plotting/_plotly/scatter.py
verticapy/plotting/base.py
verticapy/tests_new/machine_learning/vertica/test_linear_model.py

- adding the possibility to format numbers: closes https://jira.verticacorp.com/jira/browse/VER-93891
- correcting the bug on EXPLAIN: closes https://jira.verticacorp.com/jira/browse/VER-94226
- adding BETA version of report: closes https://jira.verticacorp.com/jira/browse/VER-94231
- correcting scatter bug: closes [#1210](https://github.com/vertica/VerticaPy/issues/1210) -https://jira.verticacorp.com/jira/browse/VER-94239
- correcting the statement bug: https://jira.verticacorp.com/jira/browse/VER-93970
- adding new options

[QPROF] Multiple Improvements

---

verticapy/__init__.py
verticapy/performance/vertica/qprof.py
verticapy/performance/vertica/tree.py
verticapy/plotting/base.py

closes:
- https://jira.verticacorp.com/jira/browse/VER-93874 - new param: display_legend
- https://jira.verticacorp.com/jira/browse/VER-94067?filter=-1
- https://jira.verticacorp.com/jira/browse/VER-94224?filter=-1
TODO:
https://jira.verticacorp.com/jira/browse/VER-93871?filter=-1 https://jira.verticacorp.com/jira/browse/VER-94032?filter=-1 https://jira.verticacorp.com/jira/browse/VER-93888?filter=-1

[QPROF] Many improvements

---

verticapy/_utils/_display.py
verticapy/performance/vertica/qprof.py
verticapy/performance/vertica/qprof_interface.py
verticapy/performance/vertica/qprof_utility.py
verticapy/performance/vertica/tree.py
verticapy/tests_new/performance/vertica/collection/test_export_simple.py
verticapy/tests_new/performance/vertica/test_qprof.py

Closes:
https://jira.verticacorp.com/jira/browse/VER-94032 https://jira.verticacorp.com/jira/browse/VER-94138 https://jira.verticacorp.com/jira/browse/VER-93888 https://jira.verticacorp.com/jira/browse/VER-94370 https://jira.verticacorp.com/jira/browse/VER-94371
Started:
https://jira.verticacorp.com/jira/browse/VER-93189 https://jira.verticacorp.com/jira/browse/VER-93871

[QPROF] Closing many issues

---

verticapy/jupyter/html/style.css

vDataFrame Style - Added CSS to change the size of the up and down sorting arrows on table

---

verticapy/performance/vertica/qprof_interface.py
verticapy/tests_new/machine_learning/vertica/test_tfidf.py

The index of "jump to query" was different from "get_queries". Fixed it.

Bugfix - QueryProfilerInterface - Index for Jump To Query

---

verticapy/performance/vertica/qprof.py
verticapy/performance/vertica/tree.py
verticapy/tests_new/machine_learning/vertica/test_tfidf.py

- Supporting DML
- Adding clearer error messages
- Trying to correct a test bug

DML Support + few corrections

---

verticapy/performance/vertica/qprof_utility.py
verticapy/performance/vertica/tree.py

Finalizing DML

---

verticapy/performance/vertica/qprof.py
verticapy/performance/vertica/qprof_interface.py

+ Widget to toggle the projection display
+ Also added information on query execution success.

QueryProfiler Interface Update - Added projection display widget + Query Execution Success info

---

verticapy/performance/vertica/qprof.py
verticapy/performance/vertica/qprof_interface.py
verticapy/performance/vertica/tree.py

- insertion
- correction of dml

[QPROF] Adding insertion + bug correction

---

verticapy/performance/vertica/qprof.py

[QPROF] Finalising the insert

---

verticapy/performance/vertica/qprof.py

bugfix - QueryProfilerInterface - Query Success Flag

---

verticapy/_utils/_parsers.py
verticapy/performance/vertica/collection/collection_tables.py
verticapy/performance/vertica/collection/profile_import.py
verticapy/plotting/_plotly/machine_learning/kmeans.py
verticapy/tests_new/machine_learning/vertica/test_base_model_methods.py
verticapy/tests_new/machine_learning/vertica/test_linear_model.py
verticapy/tests_new/machine_learning/vertica/test_model_management.py
verticapy/tests_new/machine_learning/vertica/test_tree_model.py
verticapy/tests_new/performance/vertica/collection/test_export_simple.py

Closes: 
https://jira.verticacorp.com/jira/browse/VER-94645?filter=-1 
https://jira.verticacorp.com/jira/browse/VER-94644?filter=-1
https://jira.verticacorp.com/jira/browse/VER-93871?filter=-1
Correcting some tests.

Correcting QPROF explain plan + DC SLOW EVENT + test correction

---

verticapy/machine_learning/model_selection/hp_tuning/param_gen.py
verticapy/tests_new/performance/vertica/test_qprof.py

- correcting many bugs
* unit tests
* AutoML

Correct Bugs

---

docs/source/user_guide_data_preparation.rst
setup.py
verticapy/__init__.py
verticapy/machine_learning/vertica/ensemble.py
verticapy/tests/vModel/test_xgb_classifier.py
verticapy/tests_new/machine_learning/vertica/test_linear_model.py
verticapy/tests_new/machine_learning/vertica/test_tree_model.py

VerticaPy Documentation Update : Fixed link + RFClassifier description

---

docs/source/machine_learning_vertica_classification.rst
docs/source/udf.rst
docs/source/verticapylab_gs.rst
docs/source/verticapylab_gs_queryprofiler.rst
verticapy/performance/vertica/qprof.py

- Made the QueryProfiler more intuitive.

Sphinx Complication Doc Fixes

---

docs/refresh.sh
docs/source/api.rst
docs/source/cicd_codecov.rst
docs/source/conf.py
docs/source/contribution_guidelines_code.rst
docs/source/contribution_guidelines_code_auto_doc.rst
docs/source/contribution_guidelines_code_auto_doc_example.rst
docs/source/contribution_guidelines_code_example.rst
docs/source/contribution_guidelines_code_misc.rst
docs/source/contribution_guidelines_code_unit_tests.rst
docs/source/getting_started.rst
docs/source/machine_learning_vertica_classification.rst
docs/source/performance_vertica.rst
docs/source/udf.rst
docs/source/user_guide.rst
docs/source/verticapylab_gs.rst
docs/source/verticapylab_gs_queryprofiler.rst
docs/source/whats_new.rst
docs/source/whats_new_v1_0_0.rst
docs/source/whats_new_v1_0_2.rst
docs/source/whats_new_v1_0_3.rst
docs/source/whats_new_v1_0_4.rst
verticapy/performance/vertica/qprof.py

- Fixing typos
- Correcting links

VerticaPy Doc - Copyedits

---

verticapy/machine_learning/vertica/tsa/base.py
verticapy/performance/vertica/__init__.py
verticapy/performance/vertica/collection/profile_import.py
verticapy/performance/vertica/qprof.py
verticapy/performance/vertica/qprof_stats_tests.py
verticapy/performance/vertica/qprof_utility.py
verticapy/tests_new/machine_learning/vertica/test_base_model_methods.py

- Adding multiple improvements: 3 new steps.
- data send to client test, query event test, queue wait time test, basic check.
- should close: https://jira.verticacorp.com/jira/browse/VER-95589?filter=-1, https://jira.verticacorp.com/jira/browse/VER-95584?filter=-1, https://jira.verticacorp.com/jira/browse/VER-95588?filter=-1, https://jira.verticacorp.com/jira/browse/VER-95585?filter=-1

QPROF Improvements: New steps + first test

---

README.md
docs/Documentation Generation.md

Added a page to explain how to create documentation using sphinx

Create Documentation Generation.md

---

verticapy/__init__.py
verticapy/performance/vertica/qprof_stats_tests.py
verticapy/performance/vertica/qprof_utility.py
verticapy/performance/vertica/tree.py

- icon in case of no statistics
- adding the SQL action for Statistics
Should close: https://jira.verticacorp.com/jira/browse/VER-95750?filter=-1, https://jira.verticacorp.com/jira/browse/VER-95583?filter=-1

[QPROF] Updating Statistics

---

verticapy/performance/vertica/collection/collection_tables.py
verticapy/performance/vertica/collection/profile_import.py
verticapy/performance/vertica/qprof.py
verticapy/tests_new/performance/vertica/collection/test_export_simple.py

- Solves https://jira.verticacorp.com/jira/browse/VER-95891?filter=-1

[QProf] DCSlowEventsTable collection

---

docs/Documentation Generation.md
docs/source/machine_learning_vertica_time_series.rst
docs/source/performance_vertica.rst
docs/source/whats_new.rst
docs/source/whats_new_v1_0_5.rst
verticapy/machine_learning/vertica/tsa/arima.py

minor corrections in formatting + included instruction about "make installation"

Update Documentation Generation.md

---

verticapy/__init__.py
verticapy/performance/vertica/qprof.py
verticapy/performance/vertica/qprof_interface.py
verticapy/performance/vertica/qprof_utility.py
verticapy/performance/vertica/tree.py
verticapy/tests_new/performance/vertica/test_qprof.py

Should close: https://jira.verticacorp.com/jira/browse/VER-95847?filter=-1

[QPROF] Adding all the metrics to the tooltip

---

verticapy/performance/vertica/qprof.py
verticapy/performance/vertica/qprof_interface.py
verticapy/performance/vertica/tree.py

Should close: https://jira.verticacorp.com/jira/browse/VER-95853?filter=-1

[QPROF] Making the tooltips more consistent

---

docs/source/whats_new_v1_0_5.rst
setup.py
verticapy/__init__.py
verticapy/performance/vertica/qprof_interface.py

- versioning
TODO:
@mail4umar please update the whatsnew doc page and any missing element.

Finalising v1.0.5

---

verticapy/performance/vertica/qprof.py
verticapy/performance/vertica/qprof_utility.py
verticapy/performance/vertica/tree.py

- Simplifying the code.
- Adding more metrics.
- Correcting the metrics.
- Bonus: ALL NODES / QUERY INITIATOR icons
Should close:
- https://jira.verticacorp.com/jira/browse/VER-96021?filter=-1
- https://jira.verticacorp.com/jira/browse/VER-95956?filter=-1

[QPROF] Adding more metrics

---

verticapy/performance/vertica/qprof_interface.py

Because of changed name, need to update the dropdown options

QueryProfilerInterface - Bugfix

---

verticapy/performance/vertica/qprof.py
verticapy/performance/vertica/tree.py

- Checks on operator_id.
- Supporting NULL values.
Should close:
- https://jira.verticacorp.com/jira/browse/VER-96161?filter=-1
- https://jira.verticacorp.com/jira/browse/VER-96160?filter=-1

[QPROF] Supporting NULL Value + More Checks

---

verticapy/performance/vertica/qprof.py

- Small PR to introduce a new param.

[QPROF] New checks

---

verticapy/jupyter/html/html_template_connected.html

Now you have the option to see ALL the rows in one page.
Also the default is now 100 instead of 25

IDisplay - Default show size change

---

verticapy/jupyter/_javascript.py
verticapy/jupyter/html/style.css

Modified the javascript code to ensure that the values can be sorted.
To ensure that the style stays professional, i modified the style.css file as well.

vDataFrame idisplay - Sorting bugfix

---

verticapy/machine_learning/vertica/automl/supervised.py
verticapy/performance/vertica/qprof.py
verticapy/performance/vertica/tree.py
verticapy/plotting/_plotly/machine_learning/champion_challenger.py

- We can now customise the legend.
- We can now return individual objects.
- AutoML correction.
Should close:
https://jira.verticacorp.com/jira/browse/VER-96478?filter=-1

[QPROF] Multiple Enhancements

---

verticapy/performance/vertica/qprof.py

- Changing the default behaviour of the session control

[QPROF] Session Control

---

verticapy/performance/vertica/__init__.py
verticapy/performance/vertica/qprof_interface.py

To do:
- The METRIC part of the accordion is not working yet.

Added basic elements for QueryProfilerComparison

---

verticapy/performance/vertica/qprof_interface.py

- Ensured that the left-side controls are master and they control both the displays
- Added hourglass as waiting graphic while the tree loads
- Added an accordion for non default session parameters
Should close: [VER-96547](https://jira.verticacorp.com/jira/browse/VER-96547) and [VER-97061](https://jira.verticacorp.com/jira/browse/VER-97061)

QueryProfilerComparison - UI update

---

verticapy/__init__.py
verticapy/performance/vertica/qprof.py
verticapy/performance/vertica/tree.py

- Correcting some possible issues.

[QPROF] Small Enhancements

---

verticapy/_utils/_sql/_vertica_version.py
verticapy/machine_learning/vertica/__init__.py
verticapy/machine_learning/vertica/linear_model.py
verticapy/performance/vertica/qprof_interface.py

- no unit tests made.
- should work
should close:
- https://jira.verticacorp.com/jira/browse/VER-93164?filter=-1 (maybe another PR would be needed to handle the components for model import/export).
+ bugfix for QueryProfilerInterface

PLS Regression - PART1

---

verticapy/performance/vertica/qprof_interface.py

Added multiple upgrades:
- Made it faster by reusing the QueryProfilerInterface class
- Added frontend of operator search
- Added frontend for tooltip search
- Added session parameter tab
- Hid unnecessary functions/attributes

QueryProfielrComparison - UI enhancements

---

verticapy/performance/vertica/qprof_interface.py

- Added a tab for compelte tooltip information
- Modified QueryPRofielrComaprison class to reuse the accordion entirely

QueryProfilerInterface - UI Update

---

verticapy/__init__.py
verticapy/core/vdataframe/_plotting.py
verticapy/core/vdataframe/_sys.py
verticapy/performance/vertica/qprof.py

- Rewriting some definition.
- Should close: https://github.com/vertica/VerticaPy/issues/1303

[QPROF] Enhancement + misc

---

docs/source/_static/website/user_guides/data_exploration/churn (1).csvZone.Identifier
docs/source/_static/website/user_guides/data_exploration/churn.csv
docs/source/user_guide_data_exploration_descriptive_statistics.rst
docs/source/user_guide_data_ingestion.rst
docs/source/user_guide_introduction_best_practices.rst

This PR should close:
Introduction:
Data Ingestion:
Data exploration

Converting userguide to RST

---

docs/refresh.sh
docs/source/examples_business_battery.rst
docs/source/examples_business_booking.rst
docs/source/examples_business_spotify.rst
docs/source/examples_understand_amazon.rst
docs/source/user_guide.rst
docs/source/user_guide_data_exploration_charts.rst
docs/source/user_guide_data_exploration_correlations.rst
docs/source/user_guide_data_exploration_descriptive_statistics.rst
docs/source/user_guide_data_ingestion.rst
docs/source/user_guide_data_preparation_normalization.rst
docs/source/user_guide_data_preparation_outliers.rst
docs/source/user_guide_full_stack_complex_data_vmap.rst
docs/source/user_guide_full_stack_linear_regression.rst
docs/source/user_guide_full_stack_train_test_split.rst
docs/source/user_guide_introduction.rst
docs/source/user_guide_introduction_best_practices.rst
docs/source/user_guide_introduction_vdf.rst
docs/source/user_guide_performance_qprof.rst
verticapy/__init__.py
verticapy/performance/vertica/qprof.py
verticapy/tests_new/machine_learning/vertica/test_base_model_methods.py

[DOC FINAL]
We then need to do the following tasks:

[DOCUMENTATION] Final for v1.1.0

---

verticapy/__init__.py
verticapy/performance/vertica/qprof.py
verticapy/performance/vertica/qprof_interface.py

[Documentations] Correcting some bugs

---

verticapy/performance/vertica/qprof_interface.py

+ Also added check for QueryProfilerComparison to make sure the inputs are both the correct type.

QueryProfilerInterface update - Added cut-off threshold of metrics

---

verticapy/performance/vertica/qprof_interface.py

Now the users can use QueyrProfilerInterface objects that have multiple queries. And they can be easily navigated.

QueryProfileComparison - Added navigation for multiple queries

---

verticapy/connection/utils.py

The path variable could potentially be used maliciously. So added checks for it.

Security Enhancement - Added path validation to protect files
