vertica/VerticaPy

README.md
Update the dataset example to reference `verticapy.datasets` instead of `verticapy.learn.datasets` which throws a `ModuleNotFoundError`
=> Update dataset example

verticapy/__init__.py, verticapy/html/html_template_connected.html, verticapy/html/style.css, verticapy/javascript.py, verticapy/utilities.py, verticapy/vdataframe.py
This is 1st PR of a series whose goal will be to support interactive tables i.e dynamic tables using javascript.
For now you can test it with:
init_interactive(all_interactive=True): this will enable interactive table on all vdataframes.
vdf.idisplay(): use this method if you only one to activate interactive table on the current vdataframe.
This is achieved using the [jQuery dataTables library](https://datatables.net/). It comes with its own style, so although we can make it as similar as possible as a normal vdataframe html table there will be some differences. For now there are only the search bar, the page length and the previous/next buttons are supported but more features will be added.
The table style will be changed progressively in order to have a very dynamic one.
It has been …
=> Integrate JQuery datatables into vdataFrame tables (#345)

verticapy/connect.py
This fixes a SyntaxError with the backup_server_node setting. The code attempts to execute: id_port = 11.111.111.1 when the desired functionality is id_port = '11.111.111.1'.
=> Fix connection backup_server_node parameter

verticapy/html/html_template_connected.html, verticapy/html/style.css, verticapy/javascript.py
This updates the interactive mode by:
- keeping the index white
- The footer was confusing so I made a simple message that just tells the range of rows that are currently being displayed.
Here is an example of a table:
Closes: #354
=> Update vDataFrame interactiveness

verticapy/utilities.py
@oualib Please check it out. 
Currently, we cannot search for number of files in the server so wildcard search for number of files ONLY works for local. But currently infer DDL does not work for local so counting max files is essentially useless. but I have put it anyway for future. 
close #397
=> Adding complex datatype parameter for read_json

verticapy/toolbox.py, verticapy/utilities.py
- We use temp local table when there is many DBLINK calls.
- It finalises the DBLINK integration.
=> Support of many DBLINK calls

verticapy/_utils/_sql/_vertica_version.py, verticapy/learn/metrics/__init__.py, verticapy/machine_learning/metrics/__init__.py, verticapy/machine_learning/metrics/classification.py, verticapy/machine_learning/model_selection/hp_tuning/cv.py, verticapy/machine_learning/model_selection/hp_tuning/plotting.py, verticapy/machine_learning/model_selection/model_validation.py, verticapy/machine_learning/model_selection/variables_selection.py, verticapy/machine_learning/vertica/base.py, verticapy/machine_learning/vertica/neighbors.py
- multilabel_confusion_matrix is a wrong name for what it is. We've built one unified confusion_matrix function
- Parameter scores is replaced to None as the one of sklearn.
TODO:
- add the binary option.
=> Classification Metrics: Parameters Normalization

verticapy/tests/vDataFrame/test_vDF_plot_plotly.py, verticapy/tests_new/plotting/plotly/machine_learning/test_plotly_kmeans.py
Added some more margin for the number of elements in the plot. This is because the test is based upon sampling and randomness of the data created, there could be a variety of number of elements in there.
- Also renamed a class in the old tests to correctly reflect the type of plot test
=> Bug fix for voronoi chart unit test

verticapy/plotting/_matplotlib/outliers.py, verticapy/tests_new/plotting/matplotlib/test_matplotlib_outliers.py
Created an IF condition for the 1D contour plot using matplotlib.
Unless the Z score is larger than the threshold, there will not be any contour plot.
Previously, it was unchecked and created errors because the levels for contours were decreasing.
=> Bug Fix for 1D Outliers plot using matplotlib

verticapy/core/vdataframe/_multiprocessing.py, verticapy/plotting/_utils.py, verticapy/plotting/base.py
I marked the functions that might be missing docstrings. Some of these might be internal (so might not be absolutely necessary to add docstrings), but thought it best to identify them just in case. If none of these functions require descriptions, we can just close this PR.
=> Missing docstrings

verticapy/machine_learning/metrics/classification.py
New method added to compute roc_auc_score using either "micro" or "macro" averaging. 
The format is as follows:
roc_auc_score(*name of y_true columns*, *list of columns with score for all the classes*, *input relation/vDataFrame*, *average kind*, *list of labels*.
note that the list of labels and y_score columns should be in a matching order i.e. the first element in the labels list should match the first element in the score list.
For example: 
```python
import verticapy.machine_learning.metrics.classification as vpy_metrics
vpy_metrics.roc_auc_score("y_true_num", ["y_prob0","y_prob1","y_prob2"], vdf,average="macro",labels=['0','1','2'])
```
Next: Need to update unit tests by un-skipping the relevant tests.
closes #641
=> roc_auc_score for multiclass classification using micro and macro averaging

verticapy/plotting/_highcharts/density.py, verticapy/tests_new/plotting/highcharts/test_highcharts_density.py
- corrected data labels
- un-skipped the relevant unit test
=> Bug - highcharts multi-density plot

verticapy/plotting/_matplotlib/machine_learning/importance.py, verticapy/plotting/_matplotlib/machine_learning/model_evaluation.py, verticapy/plotting/_plotly/density.py, verticapy/tests/vDataFrame/test_vDF_plot_plotly.py, verticapy/tests_new/plotting/matplotlib/machine_learning/test_matplotlib_importance.py, verticapy/tests_new/plotting/matplotlib/machine_learning/test_matplotlib_model_evaluation.py, verticapy/tests_new/plotting/plotly/test_plotly_density.py
- Added % sign on importance plot for matplotlib
- Added Y label for lift chart and cutoff curve in matplotlib
- Removed quotation marks for plotly density plot
=> plotting visual bug fixes

verticapy/core/vdataframe/_plotting.py, verticapy/plotting/_highcharts/heatmap.py
- max_cardinality / h
- HC heatmap
=> Fixing Plotting Bug

verticapy/machine_learning/metrics/classification.py
- added code
- works with following averaging methods: weighted, micro, macro and None
It works with the following syntax:
average_precision_score("y_true_num", ["y_prob0","y_prob1","y_prob2"], average="micro",vdf,labels=['0','1','2'])
where "y_true_num" is the name of the column with actual values
["y_prob0","y_prob1","y_prob2"] is the list of column names with probability values for each of the different classes
['0','1','2'] are the lsit of respective labels
close #663
=> Average Precision Score

verticapy/plotting/_plotly/heatmap.py
Now color options can be changed in heatmap using the following syntax:
data.corr(method = "pearson",color_continuous_scale=[[0,"white"],[1,"red"]])
=> Plotly Heatmap - Color options

verticapy/plotting/_matplotlib/machine_learning/regression.py
Now "color" and "colors" are both accepted as valid aprameters
=> Matplotlib Regression Plot - Color parameter fix

verticapy/datasets/loaders.py
Generators.py was already converted. This PR converts the rest of the datasets directory (really just loaders.py). Pretty straightforward, but I did run into an error displaying three of the datasets, seemingly because of non-standard characters. This is the error I received:
`test_file.py:docstring of test_file.load_amazon:39: CRITICAL: Problem with "raw" directive:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 74196: invalid start byte`
=> sphinx conversion -- the rest of datasets directory

verticapy/machine_learning/memmodel/linear_model.py
Changed docstrings of memmodel/linear_model.py to include code examples
=> modified doc string of memmodel/linear_model.py 

verticapy/core/vdataframe/_corr.py
- finalising the corr docstring file.
@mail4umar 
Please check if everything is working well. I tried to use the HTML file of datasets to represent titanic and amazon and I am not sure it will work.
Besides, should we seed the randomness for the examples? So users can reproduce the example?
Please review ASAP so I can use this methodology on new files.
=> Finalising corr's docstring

verticapy/machine_learning/vertica/linear_model.py
Draft for LinearRegression. Rest of the ml algorithm classes will follow the same syntax.
@oualib  can you please check.
=> Sphinx Docstring Update for MachineLearning/Vertica/LinearModel

verticapy/_config/config.py, verticapy/jupyter/extensions/chart_magic.py, verticapy/sql/geo/index.py, verticapy/sql/insert.py
- config file was changing color for the entire environment without reverting back
- chart magic was using verticapy.chart
- there was a warning that needed to be acknowledged
@oualib if there is a way to revert back colors then i can update this
=> Some bug fixes for doc strings

verticapy/core/vdataframe/_machine_learning.py, verticapy/core/vdataframe/_plotting.py, verticapy/core/vdataframe/_scaler.py, verticapy/machine_learning/vertica/automl/clustering.py, verticapy/machine_learning/vertica/automl/dataprep.py, verticapy/machine_learning/vertica/preprocessing.py, verticapy/tests/udf/pmath.py, verticapy/tests/udf/test_udf.py, verticapy/tests/vDataFrame/test_vDF_feature_engineering.py, verticapy/tests/vDataFrame/test_vDF_preprocessing.py, verticapy/tests_new/core/vdataframe/test_normalize.py
- important as it confuses user.
- .normalize method is still available but is not an alias of scale
=> Renaming "normalize" to the correct name

verticapy/machine_learning/vertica/cluster.py, verticapy/machine_learning/vertica/ensemble.py, verticapy/machine_learning/vertica/linear_model.py
- Fixed Anomaly Plot
- Updated Docstring for sphinx
=> Bugfix _ Isolation Forest Anomaly Plot

verticapy/machine_learning/vertica/cluster.py, verticapy/machine_learning/vertica/ensemble.py
@oualib Please check. Also suggest if we want to add more details like model.cluster_i_ss_ or model.children_right_ etc.
=> Sphinx Docstring Update - Bisecting KMeans

verticapy/machine_learning/vertica/naive_bayes.py
@oualib please suggest if we want to add more details on multiclass metrics.
=> sphinx docstring - ml/vertica/naive_bayes

verticapy/machine_learning/memmodel/cluster.py, verticapy/machine_learning/metrics/classification.py, verticapy/machine_learning/vertica/base.py, verticapy/machine_learning/vertica/cluster.py
- I have commented out some functions such as model.report and model.to_python because of bugs.
=> Sphinx Docstring Update - Nearest Centroid

verticapy/machine_learning/memmodel/naive_bayes.py, verticapy/tests_new/__init__.py, verticapy/tests_new/core/vdataframe/test_agg.py, verticapy/tests_new/core/vdataframe/test_math.py, verticapy/tests_new/core/vdataframe/test_rolling.py
UT code for math and rolling functions.
Two observations:
1) log function in apply_fun - Expected log arg from vertica doc is **log (base, expression)**. However, Verticapy is considering **log (expression, base)** i.e. in reverse order.
titanic["age"].apply_fun(func = "log")
2) mad (median absolute deviation) function in analytic is using mean instead of median.
titanic.analytic(func="mad", columns="age", name="mad")
=> 746 tests vdataframe math and rolling

verticapy/machine_learning/vertica/preprocessing.py
- Scaler
- StandardScaler
- RobustScaler
- MinMaxScaler
- Balance
=> Sphinx Docstring for Preprocessing 

verticapy/tests_new/machine_learning/metrics/test_classification_metrics.py
UT for average_precision_score
=> UT for average_precision_score

verticapy/machine_learning/vertica/linear_model.py, verticapy/tests_new/machine_learning/vertica/test_base_model_methods.py
=> Correcting linear models hierarchy

verticapy/_utils/_sql/_vertica_version.py, verticapy/machine_learning/vertica/__init__.py, verticapy/machine_learning/vertica/base.py, verticapy/machine_learning/vertica/linear_model.py, verticapy/machine_learning/vertica/model_management.py, verticapy/machine_learning/vertica/tsa.py, verticapy/plotting/_highcharts/__init__.py, verticapy/plotting/_highcharts/machine_learning/tsa.py, verticapy/plotting/_highcharts/range.py, verticapy/plotting/_matplotlib/__init__.py, verticapy/plotting/_matplotlib/machine_learning/tsa.py, verticapy/plotting/_plotly/__init__.py, verticapy/plotting/_plotly/line.py, verticapy/plotting/_plotly/machine_learning/tsa.py, verticapy/plotting/base.py, verticapy/tests_new/machine_learning/vertica/test_linear_model.py, verticapy/tests_new/machine_learning/vertica/test_tree_model.py
Entire implementation of TS models.
TODO:
1. @vikash018 Unit Tests
2. @mail4umar Entire Docstrings
Those should be done in two different PRs
=> Adding TIME SERIES models (AR, MA, ARMA, ARIMA)

verticapy/machine_learning/vertica/tsa.py, verticapy/plotting/_highcharts/machine_learning/tsa.py, verticapy/plotting/_matplotlib/machine_learning/tsa.py, verticapy/plotting/_plotly/machine_learning/tsa.py, verticapy/plotting/base.py
- HC correction
- handling full forecasting and one step ahead forecasting
- possibility to filter ts steps
- improve the quality of the scores and report
=> Time Series improvement

.github/workflows/master-codecov.yml, tox.ini
The installation of tensorflow must be skipped on master
=> Fixing the after-merge test failures on master

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/issue.yml
Per a request from @oualib, I investigate how we can reshape our "Issues" tab. The changes proposed in this PR is going to provide three options when trying to create a new issue:
- Trackable Change: This will create a new issue similar to what we had before.
- Bug Reports (and other issues): This will navigate the page to the "Potential bug" category in the "Discussion" tab.
- Feature Request / Enhancement: This will navigate the page to the "Ideas" category in the "Discussion" tab.
This PR will resolve issue #1098.
=> Reshaping the template of the Issues tab

verticapy/plotting/_plotly/scatter.py, verticapy/tests_new/plotting/base_test_files.py
Previously, when using the "by" option, the data type for x-axis and y-axis became string. This caused the plot to be misleading as it was more of a categorial axis than numerical.
I fixed that.
+ I added a Unit Test to ensure this is caught in the future. 
Todo:
- Need similar unit tests for highcharts and matplotlib
=> Plotly Scatter Plot - bugfix + Unit Test update

verticapy/_utils/_sql/_vertica_version.py, verticapy/machine_learning/vertica/base.py, verticapy/mlops/model_versioning/base.py
The mode versioning was added to Vertica 12.0.4. I had forgotten to check the version of the database when I implemented its VerticaPy API.
=> Vertica version for model versioning

verticapy/machine_learning/vertica/base.py, verticapy/machine_learning/vertica/ensemble.py
Previously we would get ``nan`` values for training_row_count. That produced an error. 
Now such ``nan`` values from the server side will be treated as follows:
if traning_row_count== NaN:
if not node.isRoot():
set traning_row_count to 0
else:
discard the tree
=> Added code to overwrite the tree when Nan values are present

verticapy/_utils/_sql/_format.py, verticapy/performance/vertica/qprof.py, verticapy/performance/vertica/qprof_interface.py
made the following changes to QueryProfielrInterface.get_qplan_tree;
- Added theQuery Execution Time for each query
- Added a display of the Query 
Also fixed format_query:
Previously there was no way to fetch the html representation of a formatted query if you don't print it. I updated it such that this can now give the html without printing:
```
format_query(query, print_sql=False)
```
=> Qprof Interface Update + format_query

verticapy/tests/vDataFrame/test_vDF_utilities.py
Commit 3aa0b697b25ad accidentally changed [verticapy/tests/vDataFrame/test_vDF_utilities.py](https://github.com/vertica/VerticaPy/compare/master...jslaunwhite-microfocus:VerticaPyFork:bugfix/fixup_accidental_test_changes?expand=1#diff-65ecb09eb383d217f8c0443e07ef52ef9c0dee915b2c780b7595b578c1e7375c). The accidental change caused a conflict with Vikash's PR.
Checked out file to 8addeab0, reverting the change of 3aa0b697b.
=> Revert unnecessary test changes

verticapy/performance/vertica/collection/collection_tables.py, verticapy/performance/vertica/collection/profile_import.py
When the users import a queryprofiler object **from a file** and provide a schema and key combination that has already been used, it will now raise an error instead of overwriting/appending.
```
qprof = QueryProfiler.import_profile(target_schema=target_schema_val,
key_id=key_val,
filename=file_val,
auto_initialize = False                                          
```
=> Queryprofiler import restriction for same target_schema and key_id combination

.github/workflows/black.yml, .github/workflows/ci.yaml, .github/workflows/master-codecov.yml, .github/workflows/pylint.yml, .github/workflows/python-publish.yml
The main improvement in this PR is changing the type of release trigger in the python-publish.yml workflow to [published].
According to this page the [published] type covers a broader range of events.
https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=published#release
created: A draft was saved, or a release or pre-release was published without previously being saved as a draft.
published: A release, pre-release, or draft of a release was published.
Besides, I update the checkout actions in all workflows to version 4.
=> Improving workflows

verticapy/performance/vertica/collection/profile_import.py, verticapy/performance/vertica/qprof.py, verticapy/performance/vertica/qprof_utility.py
Previously, the provided key would not be used unless ```overwrite``` parameter was turned to ```True```. Now it will check if such a table with the exact key and schema exists, if it doesn't then it will use the user provided key. 
+ Brought the function "_get_set_of_tables_in_schema" inside qprof_utility
=> Bugfix for creating QueryProfiler object with transaction, key and schema.

verticapy/performance/vertica/qprof.py, verticapy/tests_new/machine_learning/vertica/test_tfidf.py, verticapy/tests_new/performance/vertica/test_qprof.py
Speeding up the query by adding the filter to sift through only the desired transaction ids and statement ids.
Unit test: Updated the unit test for ``get_queries`` function. Included the new parameters for starting and ending timestamp.
Also skipped the test for tfidf with variable ``with_words``. This is not working with the compatible version of tensorflow in python 3.12.
=> QueryProfiler Update: Speed-up + Start and End Time Information added

verticapy/core/parsers/pandas.py, verticapy/core/tablesample/base.py, verticapy/core/vdataframe/_io.py, verticapy/performance/vertica/collection/collection_tables.py
Now the users can create a vDataFrame from an empty pandas dataframe which has column names.
For example:
```
import pandas as pd
from verticapy import read_pandas
df = pd.DataFrame()
df = df.reindex(columns = ["col1", "col2"])
read_pandas(df)
```
This also fixes a bug for exporting profiles from QueryProfiler. Sometimes, there would be certain tables missing while profiling. This would result in an error while exporting. Now the profiles can be exported even with those missing tables.
=> Bugfix - Empty vDataFrame + export_profile

.github/workflows/ci.yaml, .github/workflows/master-codecov.yml
Apparently, the address for vertica-ce releases has changed from vertica directory to opentext directory after 24.1.
Also, we had fixed the Ubuntu version awhile ago to avoid a versioning problem for running our unit tests. I hope that the problem is resolved by now.
=> Updating ci/cd tools

verticapy/performance/vertica/qprof_interface.py
- Changed inheritance of QueryProfileInterface so that Stats can also be used in the same class
- Changed the ``get_qsteps`` function name which was causing issues with parent class.
=> QueryProfilerInterface and QueryProfilerStats - reconciliation

verticapy/jupyter/_javascript.py, verticapy/performance/vertica/collection/profile_import.py, verticapy/performance/vertica/qprof.py
When very small interval values were being parsed, there was a COPY error because of mismatch of data types.
This fixes that by making sure the runnning_time is the correct data type.
it should solve: https://jira.verticacorp.com/jira/browse/VER-95728
Aslo Fixed an idisplay bug.
=> QueryProfiler Import - Bugfix - Small interval values

verticapy/__init__.py, verticapy/performance/vertica/qprof.py, verticapy/performance/vertica/tree.py
Should close:
- https://jira.verticacorp.com/jira/browse/VER-96476?filter=-1
=> [QPROF] Updating session params

verticapy/machine_learning/vertica/linear_model.py, verticapy/machine_learning/vertica/model_management.py
Should close:
- https://jira.verticacorp.com/jira/browse/VER-93164?filter=-1
=> [PLS Regression] Finalizing the algorithm.

verticapy/jupyter/_widgets.py
In the previous PR, we switched display -> print_message. 
but the additional `display` option was skipped for some of the displays causing the QueryProfiler hindering the display of QueryProfiler tree
=> Bugfix for display

verticapy/performance/vertica/qprof_interface.py
- Fixed sync bug
- Added sync button for more control
=> QueryProfilerComparison - UI update

verticapy/__init__.py, verticapy/_typing.py, verticapy/core/vdataframe/_fill.py, verticapy/core/vdataframe/_plotting.py, verticapy/core/vdataframe/_sys.py, verticapy/plotting/_matplotlib/bar.py, verticapy/plotting/_matplotlib/barh.py, verticapy/plotting/_matplotlib/pie.py, verticapy/plotting/_matplotlib/spider.py, verticapy/plotting/_plotly/bar.py, verticapy/plotting/_plotly/barh.py, verticapy/plotting/_plotly/pie.py, verticapy/plotting/base.py, verticapy/tests/sql/test_sql.py, verticapy/tests/utilities/test_utilities.py, verticapy/tests_new/core/vdataframe/test_sys.py, verticapy/tests_new/mlops/test_model_tracking.py
- multiple corrections
- it is now possible to draw plots without agg
Should close:
- https://github.com/vertica/VerticaPy/issues/1029
- https://github.com/vertica/VerticaPy/issues/1286
=> [Plot] Enhancements + Bug Fixes

verticapy/performance/vertica/collection/profile_import.py
Previously, if there was any empty table in the tar file, it would break the code. Now, it will try to create the table and print a warning if there was an issue.
=> Bugfix: QueryProfiler Import - Exception for when missing values in one of the tables

verticapy/core/vdataframe/_plotting.py, verticapy/plotting/_highcharts/bar.py, verticapy/plotting/base.py
In this PR I added the functionality for a three-tier drilldown. This was necessary to plot three-tier plots for query step time using qprof.get_qsteps().
Below is the sample syntax:
``` 
import verticapy as vp
data = vp.vDataFrame({
"gender": ['M', 'M', 'M', 'F', 'F', 'F', 'F'],
"age": [20, 22, 23, 19, 21, 27, 24],
"grade": ['A','B','C','A','B','B', 'B'],
"status": ["pass", "pass", "fail", "fail", "pass", "fail", "fail"],
"score": [0.99, 0.71, 0.66, 0.92, 0.79, 0.71, 0.77],
"salary": [21000, 22000, 10000, 32000, 17000, 23000, 12000],
})
vp.set_option("plotting_lib", "highcharts")
data.bar(["grade", "gender", "status"], kind = "drilldown")
```
=> Three tier drill down highcharts

verticapy/_utils/_sql/_format.py, verticapy/tests_new/_utils/__init__.py, verticapy/tests_new/_utils/_sql/__init__.py, verticapy/tests_new/_utils/_sql/test_format.py
Previously, we never encountered namespace issue for QueryProfiler. 
But it turns out that Eon mode has namespaces. The current function `schema_relation` which is used inside the `get_qplan_tree` would give an error if a relation name like "name_space.schema.table" was provided. Now, I have added a handling for such a case.
The function `schema_relation` would return below for the case of "name_space.schema.table":
schema = 'name_space.table'
relation_name = 'table'
=> BugFix - QueryProfiler - Added handling for namespace

verticapy/core/vdataframe/_filter.py
closes #1349 
When using the filter function, the query was "cleansed" unnecessarily and this caused it to miss some intentional indenting. 
By not cleaning the query for filter, I have fixed the issue.
=> Made sure the query is not altered that is passed on to the database

verticapy/performance/vertica/qprof.py, verticapy/performance/vertica/qprof_interface.py
i have created helper functions to process the queue_time and run_time values for the QueryProfiler object.
For the QueryProfilerInterface, I have added checks for cases when the values could be None. 
This will make the QueryProfilerInterface support older qprofs.
=> Bugfix - QueryProfilerInterface gave error when there was no queue time
